// AUTOGENERADO desde texts.json (split-texts). NO editar a mano —
// editar lib/texts.json y regenerar con scripts/split-texts.mjs.

export const dashboard = {
  "club_label": "Club activo",
  "role_pending": "pendiente",
  "overview": {
    "title": "Panel operativo",
    "description": "Consulta el contexto actual del club y entra al modulo correcto segun tu rol.",
    "secretaria_title": "Operacion diaria",
    "tesoreria_title": "Control financiero",
    "settings_title": "Configuracion del club",
    "settings_description": "Administra miembros, cuentas, categorias y actividades del club activo con acceso exclusivo para Admin.",
    "visible_accounts_label": "Cuentas visibles",
    "recent_movements_label": "Movimientos recientes",
    "total_balance_label": "Saldo total visible",
    "open_module_cta": "Abrir modulo",
    "open_settings_cta": "Abrir configuracion"
  },
  "feedback": {
    "active_club_updated": "Actualizamos el club activo correctamente.",
    "club_not_available": "No tienes acceso al club seleccionado.",
    "forbidden": "No pudimos actualizar el club activo.",
    "session_opened": "La jornada del dia fue abierta correctamente.",
    "session_closed": "La jornada del dia fue cerrada correctamente.",
    "session_open_failed": "No pudimos abrir la jornada. Vuelve a intentarlo.",
    "session_close_failed": "No pudimos cerrar la jornada. Vuelve a intentarlo.",
    "movement_created": "El movimiento fue creado con exito bajo el ID {movementId}.",
    "movement_create_failed": "No pudimos registrar el movimiento. Vuelve a intentarlo.",
    "movement_updated": "La imputacion del movimiento fue actualizada correctamente.",
    "movement_update_failed": "No pudimos actualizar el movimiento. Vuelve a intentarlo.",
    "movement_integrated": "El movimiento pendiente fue integrado correctamente.",
    "transfer_created": "La transferencia interna fue registrada correctamente.",
    "fx_operation_created": "La operacion de cambio de moneda fue registrada correctamente.",
    "consolidation_completed": "La fecha seleccionada fue consolidada correctamente.",
    "session_already_exists": "La jornada del dia ya fue abierta.",
    "session_not_open": "No hay una jornada abierta para cerrar.",
    "previous_session_still_open": "Existe una jornada anterior sin cerrar. Cerrala antes de abrir una nueva.",
    "session_required": "Debes abrir la jornada antes de registrar movimientos.",
    "movement_not_editable": "No encontramos un movimiento editable en la jornada abierta.",
    "movement_date_required": "Debes seleccionar una fecha para el movimiento.",
    "account_required": "Debes seleccionar una cuenta.",
    "category_required": "Debes seleccionar una sub categoria.",
    "movement_type_required": "Debes seleccionar un tipo de movimiento.",
    "concept_required": "Debes completar el concepto.",
    "currency_required": "Debes seleccionar una moneda.",
    "amount_required": "Debes completar el importe.",
    "amount_must_be_positive": "El importe debe ser mayor a cero.",
    "invalid_account": "La cuenta seleccionada no es valida para el club activo.",
    "invalid_category": "La sub categoria seleccionada no es valida para el club activo.",
    "invalid_activity": "La actividad seleccionada no es valida para el club activo.",
    "invalid_currency": "La moneda seleccionada no es valida para la cuenta.",
    "source_account_required": "Debes seleccionar una cuenta origen.",
    "target_account_required": "Debes seleccionar una cuenta destino.",
    "accounts_must_be_distinct": "Las cuentas origen y destino deben ser distintas.",
    "invalid_transfer": "La transferencia no es valida para las cuentas o moneda seleccionadas.",
    "insufficient_funds": "La cuenta no tiene saldo suficiente para completar la operacion.",
    "source_currency_required": "Debes seleccionar una moneda origen.",
    "target_currency_required": "Debes seleccionar una moneda destino.",
    "currencies_must_be_distinct": "Las monedas origen y destino deben ser distintas.",
    "source_amount_required": "Debes completar el importe origen.",
    "target_amount_required": "Debes completar el importe destino.",
    "invalid_fx_operation": "La operacion de cambio no es valida para las cuentas o monedas seleccionadas.",
    "movement_not_found": "No encontramos el movimiento pendiente para la consolidacion seleccionada.",
    "invalid_movement_date": "La fecha del movimiento no es valida.",
    "invalid_match": "La coincidencia seleccionada ya no es valida para integrar.",
    "consolidation_date_required": "Debes seleccionar una fecha para consolidar.",
    "consolidation_already_completed": "La fecha seleccionada ya fue consolidada previamente.",
    "consolidation_has_invalid_movements": "No puedes consolidar mientras existan movimientos invalidos pendientes.",
    "invalid_receipt_format": "El recibo ingresado no cumple con un formato valido del club activo.",
    "invalid_calendar_event": "El evento de calendario seleccionado no es valido para el club activo.",
    "no_accounts_available": "No hay cuentas disponibles para validar la jornada en el club activo.",
    "declared_balance_required": "Debes completar el saldo declarado de todas las cuentas.",
    "declared_balance_invalid": "Todos los saldos declarados deben ser importes validos.",
    "adjustment_category_missing": "No encontramos la sub categoria de ajustes contables para registrar diferencias.",
    "infrastructure_incomplete": "No pudimos completar la accion porque la base remota no tiene todas las migraciones aplicadas. Actualiza Supabase y vuelve a intentarlo.",
    "unknown_error": "No pudimos completar la accion. Vuelve a intentarlo."
  },
  "club_selector": {
    "label": "Cambiar club activo",
    "helper": "Selecciona otro club para cambiar el contexto operativo.",
    "loading": "Actualizando club activo..."
  },
  "treasury": {
    "section_eyebrow": "Operaciones del día",
    "title": "Secretaría",
    "description": "Gestión de jornada, movimientos y transferencias de caja.",
    "balances_card_title": "Saldos de cuentas",
    "balances_card_description": "Consulta el saldo acumulado historico de cada cuenta visible del club activo.",
    "balances_total_label": "Total acumulado",
    "balances_unresolved": "No pudimos cargar los saldos acumulados. Recarga la pantalla para volver a intentarlo.",
    "detail_accounts_cta": "Ver detalle de cuentas",
    "balances_visible_title": "Saldos visibles",
    "balances_visible_description": "Cuentas operadas por Secretaria",
    "session_card_label": "Gestion de jornada",
    "session_meta_opening": "Apertura",
    "session_meta_closing": "Cierre",
    "session_meta_movements": "Movimientos",
    "session_meta_balance_current": "Saldo actual",
    "session_meta_not_registered": "No registrada",
    "session_meta_movements_count": "{count} cargados",
    "session_pending_message": "La jornada de hoy aun no fue abierta. No es posible cargar movimientos.",
    "movements_filter_all_accounts": "Todas las cuentas",
    "actions_card_eyebrow": "Gestion de jornada",
    "actions_card_title": "Gestion de jornada",
    "actions_card_description": "Opera la jornada y abre los formularios desde modales.",
    "actions_card_closed_description": "La jornada ya fue cerrada. No se encuentra disponible para carga de movimientos.",
    "actions_card_unresolved_description": "No pudimos resolver el estado de la jornada. Recarga la pantalla para volver a intentarlo.",
    "movement_modal_description": "Ingresos o egresos",
    "transfer_modal_description": "Entre cuentas internas",
    "close_session_flow_description": "Finalizar jornada actual",
    "open_session_flow_description": "Habilitar jornada actual",
    "movements_card_title": "Movimientos de la jornada",
    "movements_card_description": "registrados",
    "movements_edit_cta": "Editar",
    "movements_empty": "Todavia no hay movimientos registrados.",
    "movements_unresolved": "No pudimos cargar los movimientos del dia. Recarga la pantalla para volver a intentarlo.",
    "movements_concept_label": "Concepto",
    "movements_amount_label": "Monto",
    "movements_account_label": "Cuenta",
    "movements_detail_label": "Detalle del movimiento",
    "movements_actions_label": "Acciones",
    "movements_created_by_label": "Registrado por",
    "detail_cta": "Ver detalle",
    "detail_eyebrow": "Detalle",
    "detail_title": "Detalle de cuenta",
    "detail_description": "Consulta saldos e historial de movimientos de la cuenta seleccionada.",
    "detail_account_label": "Cuenta seleccionada",
    "detail_activity_label": "Actividad:",
    "detail_calendar_label": "Calendario:",
    "detail_transfer_label": "Transferencia:",
    "detail_fx_label": "Cambio de moneda:",
    "detail_empty_movements": "No hay movimientos registrados para esta cuenta.",
    "detail_pagination_previous_cta": "Anterior",
    "detail_pagination_next_cta": "Siguiente",
    "detail_pagination_status": "Pagina {current} de {total}",
    "detail_pagination_range": "Mostrando {from}-{to} de {total}",
    "detail_receipt_label": "Recibo:",
    "detail_uncategorized_category": "Sin categoria",
    "account_switch_label": "Cambiar cuenta",
    "session_label": "Estado de jornada",
    "session_open": "Abierta",
    "session_closed": "Cerrada",
    "session_not_started": "Pendiente",
    "empty_accounts": "No hay cuentas disponibles para Secretaria en el club activo.",
    "open_session_cta": "Abrir jornada",
    "close_session_cta": "Cerrar jornada",
    "open_session_flow_cta": "Apertura de jornada",
    "close_session_flow_cta": "Cierre de jornada",
    "movement_modal_cta": "Cargar movimiento",
    "edit_movement_cta": "Editar movimiento",
    "transfer_modal_cta": "Cargar transferencia",
    "movement_form_title": "Cargar movimiento",
    "movement_form_description": "Carga ingresos y egresos del dia sobre la jornada abierta.",
    "edit_form_title": "Editar movimiento",
    "edit_form_description": "Actualiza los datos operativos del movimiento seleccionado mientras la jornada siga abierta.",
    "transfer_form_title": "Cargar transferencia",
    "transfer_form_description": "Genera automaticamente un egreso y un ingreso para reflejar un traspaso interno entre cuentas.",
    "transfer_source_account_label": "Cuenta origen",
    "transfer_target_account_label": "Cuenta destino",
    "transfer_target_account_helper": "Debe ser distinta a la cuenta origen.",
    "transfer_target_account_currency_error": "La cuenta destino no admite la moneda seleccionada.",
    "transfer_default_concept": "Transferencia interna",
    "transfer_create_cta": "Registrar transferencia",
    "transfer_create_loading": "Registrando transferencia...",
    "transfer_concept_placeholder": "ej. Reposición caja chica",
    "fx_form_title": "Registrar compra o venta de moneda",
    "fx_form_description": "Genera automaticamente dos movimientos para reflejar una conversion interna entre monedas distintas.",
    "fx_source_account_label": "Cuenta origen",
    "fx_target_account_label": "Cuenta destino",
    "fx_source_currency_label": "Moneda origen",
    "fx_target_currency_label": "Moneda destino",
    "fx_source_amount_label": "Importe origen",
    "fx_target_amount_label": "Importe destino",
    "fx_default_concept": "Cambio de moneda",
    "fx_create_cta": "Crear operacion",
    "fx_create_loading": "Registrando operacion...",
    "create_loading": "Registrando movimiento...",
    "update_cta": "Guardar cambios",
    "update_loading": "Actualizando movimiento...",
    "movement_id_label": "ID de movimiento",
    "date_label": "Fecha",
    "date_helper_text": "Se asigna automáticamente a la jornada abierta.",
    "account_label": "Cuenta",
    "account_placeholder": "Seleccioná una cuenta",
    "movement_type_label": "Tipo de movimiento",
    "movement_type_placeholder": "Selecciona un tipo",
    "movement_type_ingreso_sublabel": "+ SUMA",
    "movement_type_egreso_sublabel": "– RESTA",
    "category_label": "Subcategoría",
    "category_placeholder": "Elegir...",
    "parent_category_label": "Categoría",
    "category_helper_text": "Definida por el tipo de Subcategoría.",
    "activity_label": "Actividad",
    "activity_placeholder": "Sin actividad",
    "receipt_label": "Recibo",
    "required_suffix": " *",
    "receipt_helper_example": "Ejemplo:",
    "receipt_helper_available_from": "Disponibles desde:",
    "concept_label": "Concepto",
    "concept_placeholder": "ej. Cuota social abril · Pérez Sofía",
    "currency_label": "Moneda",
    "currency_placeholder": "Selecciona una moneda",
    "amount_label": "Monto",
    "amount_helper_text": "Ingresá el valor positivo. El tipo define el impacto.",
    "expected_balance_label": "Saldo esperado",
    "declared_balance_label": "Saldo declarado",
    "difference_label": "Diferencia",
    "opening_eyebrow": "Apertura",
    "opening_title": "Apertura de jornada",
    "opening_description": "Valida los saldos iniciales de cada cuenta de Secretaria antes de habilitar la operatoria del dia.",
    "closing_eyebrow": "Cierre",
    "closing_title": "Cierre de jornada",
    "closing_description": "Valida los saldos finales de cada cuenta de Secretaria antes de cerrar la operatoria del dia.",
    "session_validation_description": "Revisa todas las cuentas visibles, ajusta los saldos declarados si hace falta y confirma la operacion.",
    "session_validation_empty": "No hay cuentas habilitadas para Secretaria en el club activo, por lo que no puedes confirmar la operacion.",
    "adjustment_preview_title": "Movimientos por diferencia",
    "adjustment_preview_description": "Si confirmas, el sistema generara un movimiento por cada diferencia detectada con la sub categoria Ajustes contables.",
    "adjustment_message": "Se registrara un ajuste para reflejar la diferencia declarada.",
    "confirm_open_session_cta": "Confirmar apertura",
    "confirm_close_session_cta": "Confirmar cierre",
    "confirm_open_session_loading": "Abriendo jornada...",
    "confirm_close_session_loading": "Cerrando jornada...",
    "navigation_loading": "Cargando pantalla...",
    "cancel_session_cta": "Cancelar",
    "back_to_dashboard_cta": "Volver al dashboard",
    "back_to_secretaria_cta": "Volver a Secretaria",
    "create_cta": "Registrar movimiento",
    "reset_cta": "Cancelar",
    "transfer_source_account_placeholder": "Seleccioná la cuenta de origen",
    "transfer_target_account_placeholder": "Seleccioná la cuenta de destino",
    "fx_source_account_placeholder": "Selecciona una cuenta origen",
    "fx_target_account_placeholder": "Selecciona una cuenta destino",
    "fx_source_currency_placeholder": "Selecciona una moneda origen",
    "fx_target_currency_placeholder": "Selecciona una moneda destino",
    "movement_types": {
      "ingreso": "Ingreso",
      "egreso": "Egreso"
    },
    "movements_see_all_cta": "Ver todos",
    "open_session_date_label": "Fecha",
    "open_session_time_label": "Hora",
    "open_session_balances_label": "Saldos de apertura por cuenta",
    "open_session_table_account": "Cuenta",
    "open_session_table_prev": "Cierre anterior",
    "open_session_table_opening": "Saldo apertura",
    "open_session_table_helper": "Cada saldo viene prellenado con el cierre anterior. Ajustalo solo si hay diferencia física verificada.",
    "open_session_diff_notes_label": "Motivo de la diferencia",
    "open_session_diff_notes_placeholder": "Una o más cuentas tienen saldo de apertura distinto al cierre anterior. Detallá el motivo.",
    "open_session_warning": "Al confirmar, se registra la apertura del día con tu usuario para **todas las cuentas** y se habilita la carga de movimientos. La acción queda en auditoría y no puede deshacerse.",
    "close_session_date_label": "Jornada",
    "close_session_time_label": "Hora",
    "close_session_summary_movements": "Movimientos",
    "close_session_summary_ingresos": "Ingresos",
    "close_session_summary_egresos": "Egresos",
    "close_session_summary_transfers": "Transferencias",
    "close_session_table_account": "Cuenta",
    "close_session_table_opening": "Apertura",
    "close_session_table_net_movements": "Mov. netos",
    "close_session_table_real_balance": "Saldo real",
    "close_session_table_difference": "Diferencia",
    "close_session_table_helper": "Ingresá el saldo físico verificado. La diferencia con el saldo esperado se calcula en vivo.",
    "close_session_diff_notes_label": "Motivo de la diferencia",
    "close_session_diff_notes_placeholder": "Una o más cuentas presentan diferencias de arqueo. Detallá el motivo (faltante, sobrante, gasto no registrado, etc.)",
    "close_session_notes_label": "Observaciones generales",
    "close_session_notes_placeholder": "Opcional",
    "close_session_negative_balance_error": "El saldo no puede ser negativo",
    "close_session_warning": "Al confirmar, se cierra la jornada para todas las cuentas, se bloquea la carga de movimientos y queda registrado el arqueo con tu usuario ({userName}). La acción no puede deshacerse.",
    "payroll": {
      "page_eyebrow": "Tesorería",
      "page_title": "Bandeja de pagos pendientes",
      "page_description": "Liquidaciones aprobadas por RRHH listas para ejecutar el pago.",
      "subtitle_counts": "{count} pendientes · Total {total}",
      "search_placeholder": "Buscar por colaborador, estructura o periodo",
      "filter_period_all": "Todos los periodos",
      "col_period": "Periodo",
      "col_member": "Colaborador",
      "col_structure": "Estructura",
      "col_total": "Monto final",
      "col_approved_at": "Aprobada el",
      "action_pay": "Pagar",
      "action_return": "Devolver a RRHH",
      "select_all_label": "Seleccionar todas",
      "select_row_label": "Seleccionar liquidacion",
      "bulk_selected_prefix": "Seleccionadas: ",
      "bulk_clear_cta": "Limpiar",
      "bulk_pay_cta": "Pagar seleccionadas",
      "empty_title": "No hay pagos pendientes",
      "empty_description": "Todas las liquidaciones aprobadas por RRHH ya fueron pagadas.",
      "empty_filter_title": "Sin resultados con esos filtros",
      "empty_filter_description": "Ajusta el periodo o la busqueda para ver mas liquidaciones.",
      "dashboard_card_eyebrow": "Pendientes de pago",
      "dashboard_card_title": "Pagos de nomina pendientes",
      "dashboard_card_description": "Liquidaciones aprobadas por RRHH listas para ejecutar el pago.",
      "dashboard_card_cta": "Abrir bandeja",
      "header_eyebrow": "Liquidaciones aprobadas por RRHH",
      "header_title": "Bandeja de pagos pendientes",
      "header_description": "Revisá las liquidaciones aprobadas y ejecutalas o devolvelas a RRHH si necesitan corrección.",
      "export_cta": "Exportar CSV",
      "summary_template": "{count} pendientes · {total} total",
      "filter_period_label": "Período",
      "filter_staff_label": "Colaborador",
      "filter_structure_label": "Estructura Salarial",
      "filter_all_period": "Todos los períodos",
      "filter_all_staff": "Todos los colaboradores",
      "filter_all_structure": "Todas las estructuras",
      "filter_count_template": "Mostrando {shown} de {total} liquidaciones",
      "filter_clear_cta": "Limpiar filtros",
      "sort_label": "Ordenar",
      "sort_period_desc": "Período (más reciente)",
      "sort_period_asc": "Período (más antiguo)",
      "sort_amount_desc": "Monto (mayor a menor)",
      "sort_amount_asc": "Monto (menor a mayor)",
      "sort_approved_desc": "Aprobación (más reciente)",
      "sort_approved_asc": "Aprobación (más antigua)",
      "sort_staff_asc": "Colaborador (A-Z)",
      "sort_staff_desc": "Colaborador (Z-A)",
      "row_approved_template": "Aprob.: {date} · {approver}",
      "row_approved_template_no_user": "Aprob.: {date}",
      "row_period_template": "Período: {period}",
      "row_aging_days_template": "+{days} días",
      "detail_expand_label": "Ver detalle",
      "detail_collapse_label": "Ocultar detalle",
      "detail_no_adjustments": "Sin ajustes registrados.",
      "detail_adjustments_title": "Ajustes aplicados"
    }
  },
  "treasury_role": {
    "eyebrow": "Finanzas del club",
    "title": "Tesorería",
    "description": "Cuentas bancarias, movimientos y conciliación.",
    "balances_total_label": "Total acumulado",
    "detail_accounts_cta": "Ver todas",
    "actions_card_eyebrow": "Gestion de Tesoreria",
    "actions_card_title": "Gestion de Tesoreria",
    "actions_card_description": "Opera Tesoreria desde accesos rapidos y formularios en modal.",
    "empty_accounts": "No hay cuentas visibles para Tesoreria en el club activo.",
    "detail_cta": "Ver detalle",
    "consolidation_cta": "Ir a conciliación",
    "consolidation_description": "Integrar movimientos pendientes",
    "view_movements_cta": "Ver movimientos",
    "movement_modal_cta": "Cargar movimiento",
    "movement_modal_description": "Ingresos o egresos propios",
    "movement_form_title": "Cargar movimiento",
    "movement_form_description": "Ingreso o egreso",
    "edit_movement_cta": "Editar movimiento",
    "edit_form_title": "Editar movimiento de Tesoreria",
    "edit_form_description": "Actualiza los datos operativos del movimiento seleccionado en las cuentas visibles para Tesoreria.",
    "fx_modal_cta": "Compra / Venta de moneda",
    "fx_modal_description": "Conversion entre monedas",
    "fx_form_title": "Compra / Venta de moneda",
    "fx_form_description": "Operación de cambio entre cuentas de distinta moneda",
    "fx_create_cta": "Registrar operación",
    "fx_create_loading": "Registrando operacion...",
    "fx_distinct_currencies_error": "La moneda origen y la moneda destino deben ser distintas.",
    "fx_operation_label": "Operación",
    "fx_operation_compra": "Compra",
    "fx_operation_venta": "Venta",
    "fx_operation_compra_sublabel": "ARS → USD",
    "fx_operation_venta_sublabel": "USD → ARS",
    "fx_exchange_rate_label": "Tipo de cambio",
    "fx_exchange_rate_helper": "Cotización MEP / dólar oficial / acordada.",
    "fx_target_amount_helper": "Calculado automáticamente.",
    "fx_concept_placeholder": "ej. Compra USD para pago proveedor internacional",
    "fx_info_banner": "Se registra un egreso en la cuenta origen y un ingreso equivalente en la cuenta destino, ambos con el mismo ID de operación para trazabilidad contable.",
    "create_cta": "Registrar movimiento",
    "create_loading": "Registrando movimiento...",
    "update_cta": "Guardar cambios",
    "update_loading": "Actualizando movimiento...",
    "navigation_loading": "Cargando pantalla...",
    "movements_card_title": "Movimientos",
    "movements_card_description": "Movimientos del periodo seleccionado en las cuentas visibles para Tesoreria.",
    "movements_empty": "No hay movimientos en el rango seleccionado.",
    "movements_window_default_days_label": "Ultimos {days} dias",
    "movements_window_custom_label": "Del {from} al {to}",
    "movements_window_count_singular": "1 registro",
    "movements_window_count_plural": "{count} registros",
    "movements_window_separator": " · ",
    "movements_filter_from_label": "Desde",
    "movements_filter_to_label": "Hasta",
    "movements_filter_apply_cta": "Aplicar",
    "movements_filter_apply_pending_cta": "Aplicando...",
    "movements_filter_reset_cta": "Restablecer",
    "movements_filter_aria_label": "Filtrar movimientos por rango de fechas",
    "staff_contract_label": "Contrato",
    "staff_contract_placeholder": "Sin asignar",
    "staff_contract_empty": "No hay contratos disponibles",
    "movements_concept_label": "Concepto",
    "movements_amount_label": "Monto",
    "movements_account_label": "Cuenta",
    "movements_detail_label": "Detalle del movimiento",
    "movements_actions_label": "Acciones",
    "movements_created_by_label": "Registrado por",
    "movement_id_label": "ID movimiento",
    "date_label": "Fecha",
    "account_label": "Cuenta",
    "account_placeholder": "Selecciona una cuenta",
    "movement_type_label": "Tipo de movimiento",
    "movement_type_placeholder": "Selecciona un tipo",
    "category_label": "Subcategoría",
    "category_placeholder": "Selecciona una subcategoría",
    "parent_category_label": "Categoría",
    "activity_label": "Actividad",
    "activity_placeholder": "Sin actividad",
    "receipt_label": "Recibo",
    "required_suffix": " *",
    "receipt_helper_example": "Ejemplo:",
    "receipt_helper_available_from": "Disponibles desde:",
    "concept_label": "Concepto",
    "currency_label": "Moneda",
    "currency_placeholder": "Selecciona una moneda",
    "amount_label": "Monto",
    "reset_cta": "Cancelar",
    "detail_transfer_label": "Transferencia:",
    "detail_fx_label": "Cambio de moneda:",
    "fx_source_account_label": "Cuenta origen",
    "fx_target_account_label": "Cuenta destino",
    "fx_source_currency_label": "Moneda origen",
    "fx_target_currency_label": "Moneda destino",
    "fx_source_amount_label": "Monto entregado",
    "fx_target_amount_label": "Monto recibido",
    "fx_source_account_placeholder": "Selecciona una cuenta origen",
    "fx_target_account_placeholder": "Selecciona una cuenta destino",
    "fx_source_currency_placeholder": "Selecciona una moneda origen",
    "fx_target_currency_placeholder": "Selecciona una moneda destino",
    "back_to_dashboard_cta": "Volver al dashboard",
    "back_to_treasury_cta": "Volver a Tesoreria",
    "movement_types": {
      "ingreso": "Ingreso",
      "egreso": "Egreso"
    },
    "sub_tab_nav_aria_label": "Sub-secciones de Tesoreria",
    "tab_resumen": "Resumen",
    "tab_payroll": "Pagos pendientes",
    "tab_payroll_count_template": "Pagos pendientes · {count}",
    "tab_cuentas": "Cuentas",
    "tab_movimientos": "Movimientos",
    "tab_conciliacion": "Conciliacion",
    "tab_cost_centers": "Centros de Costo",
    "kpi_total_balance_label": "Saldo total",
    "kpi_accounts_count_label": "cuentas activas",
    "last_movement_label": "Último movimiento",
    "no_movements_yet": "Sin movimientos",
    "cash_account_label": "Efectivo",
    "operated_by_secretaria": "Operada por Secretaría",
    "balances_section_title": "Saldos por cuenta",
    "balances_section_description": "Todas las cuentas operadas por Tesorería",
    "conciliation_status_ok": "Conciliada",
    "conciliation_status_pending": "Pendiente",
    "kpi_monthly_income_label": "Ingresos del mes",
    "kpi_monthly_expenses_label": "Egresos del mes",
    "kpi_pending_conciliation_label": "Sin conciliar",
    "kpi_pending_conciliation_meta": "movimientos pendientes",
    "quick_actions_title": "Acciones rapidas",
    "quick_actions_description": "Operaciones frecuentes",
    "all_accounts_filter": "Todas las cuentas",
    "movements_cta_movement": "+ Movimiento",
    "movements_cta_transfer": "+ Transferencia",
    "movements_cta_fx": "+ Compra/Venta",
    "transfer_modal_cta": "Cargar transferencia",
    "transfer_form_title": "Registrar transferencia",
    "transfer_form_description": "Movimiento entre cuentas del club",
    "transfer_create_loading": "Registrando transferencia...",
    "accounts_tab_description": "Cuentas visibles para Tesoreria",
    "accounts_tab_active_label": "cuentas activas",
    "accounts_tab_create_cta": "+ Nueva cuenta",
    "accounts_tab_edit_cta_label": "Editar cuenta",
    "accounts_tab_create_title": "Nueva cuenta",
    "accounts_tab_create_description": "Dar de alta una cuenta del club.",
    "accounts_tab_edit_title": "Editar cuenta",
    "accounts_tab_edit_description": "Actualiza los datos de la cuenta.",
    "account_type_bancaria": "Bancaria",
    "account_type_efectivo": "Efectivo",
    "account_type_billetera": "Billetera virtual",
    "conciliacion_tab_pending_count": "{count} pendientes",
    "conciliacion_kpi_pending_label": "Pendientes",
    "conciliacion_kpi_pending_suffix": "cargados por Secretaria",
    "conciliacion_kpi_amount_label": "Monto sin conciliar",
    "conciliacion_kpi_amount_suffix": "ARS · neto",
    "conciliacion_kpi_approved_label": "Aprobadas hoy",
    "conciliacion_kpi_approved_suffix": "por Tesoreria",
    "conciliacion_movements_title": "Movimientos a conciliar",
    "conciliacion_movements_subtitle": "Cargados por Secretaria · pendientes de aprobacion",
    "conciliacion_approve_all_cta": "Aprobar todos",
    "conciliacion_date_label": "Fecha de jornada",
    "conciliacion_date_submit_cta": "Buscar",
    "conciliacion_filter_all_accounts": "Todas las cuentas",
    "conciliacion_status_pending": "Pendiente",
    "conciliacion_status_integrated": "Integrado",
    "conciliacion_status_invalid": "Invalido",
    "conciliacion_edit_cta": "Editar",
    "conciliacion_empty_pending": "No hay movimientos pendientes para la fecha seleccionada.",
    "conciliacion_session_open_title": "La jornada todavia esta abierta",
    "conciliacion_session_open_description": "Espera a que Secretaria cierre la jornada para poder conciliar los movimientos de la fecha seleccionada.",
    "conciliacion_auto_closed_badge": "Cierre automatico",
    "conciliacion_auto_closed_description": "La jornada fue cerrada automaticamente por el sistema con saldos esperados.",
    "cost_centers": {
      "section_title": "Centros de Costo",
      "section_description": "Imputa movimientos a compromisos economicos acotados en el tiempo.",
      "subtitle_counts": "{active} activos · {inactive} inactivos · club activo",
      "kpi_active_title": "ACTIVOS",
      "kpi_active_meta": "{overdue} vencidos · revisar",
      "kpi_budget_title": "PRESUPUESTO COMPROMETIDO",
      "kpi_debts_title": "DEUDAS PENDIENTES",
      "kpi_debts_meta": "{count} CC · {currencies}",
      "search_placeholder": "Buscar por nombre...",
      "create_cta": "+ Nuevo",
      "create_full_cta": "+ Nuevo Centro de Costo",
      "save_loading": "Guardando Centro de Costo...",
      "update_loading": "Actualizando Centro de Costo...",
      "empty_title": "Todavia no hay Centros de Costo",
      "empty_description": "Crea el primer Centro de Costo para imputar movimientos y hacer seguimiento de deudas, presupuestos, eventos, sponsors y publicidad.",
      "filter_all": "Todos",
      "filter_type_debt": "Deudas",
      "filter_type_budget": "Presupuestos",
      "filter_type_event": "Eventos",
      "filter_type_sponsor": "Sponsors",
      "filter_type_advertising": "Publicidad",
      "filter_type_workday": "Jornada",
      "filter_status_active": "Activos",
      "filter_status_inactive": "Inactivos",
      "form_create_title": "Nuevo Centro de Costo",
      "form_edit_title": "Editar Centro de Costo",
      "form_name_label": "Nombre",
      "form_name_placeholder": "Ej: Mantenimiento Q2 2026",
      "form_description_label": "Descripcion",
      "form_description_placeholder": "Contexto adicional (opcional)",
      "form_type_label": "Tipo",
      "form_status_label": "Estado",
      "form_start_date_label": "Fecha inicio",
      "form_end_date_label": "Fecha fin",
      "form_currency_label": "Moneda",
      "form_amount_label": "Monto",
      "form_periodicity_label": "Periodicidad",
      "form_responsible_label": "Responsable",
      "form_disabled_hint": "No editable: el CC tiene movimientos enlazados.",
      "form_locked_in_edit_hint": "No editable: para no romper reportes ya emitidos.",
      "form_submit_cta": "Guardar",
      "form_cancel_cta": "Cancelar",
      "type_debt": "Deuda",
      "type_event": "Evento",
      "type_workday": "Jornada",
      "type_budget": "Presupuesto",
      "type_advertising": "Publicidad",
      "type_sponsor": "Sponsor",
      "status_active": "Activo",
      "status_inactive": "Inactivo",
      "periodicity_unique": "Unico",
      "periodicity_monthly": "Mensual",
      "periodicity_quarterly": "Trimestral",
      "periodicity_biannual": "Semestral",
      "periodicity_annual": "Anual",
      "badge_debt_settled": "Deuda saldada — listo para cerrar",
      "badge_budget_near_limit": "Presupuesto cerca del limite",
      "badge_budget_exceeded": "Presupuesto superado",
      "badge_goal_met": "Meta cumplida",
      "badge_overdue": "CC vencido — revisar cierre",
      "progress_executed_meta": "{executed} ejecutado · {percent}%",
      "audit_log_title": "Historial de cambios",
      "audit_log_empty": "Sin cambios registrados.",
      "audit_log_created": "Creacion",
      "audit_log_updated": "Actualizacion",
      "audit_log_closed": "Cierre",
      "detail_back_cta": "Volver a Centros de Costo",
      "detail_badges_section_title": "Indicadores",
      "detail_badges_empty": "Sin indicadores",
      "detail_movements_title": "Movimientos enlazados",
      "detail_movements_empty": "Todavia no hay movimientos imputados a este Centro de Costo.",
      "detail_movements_column_date": "Fecha",
      "detail_movements_column_type": "Tipo",
      "detail_movements_column_description": "Descripcion",
      "detail_movements_column_account": "Cuenta",
      "detail_movements_column_amount": "Monto",
      "detail_movements_column_currency": "Moneda",
      "detail_movements_unlink_cta": "Desvincular",
      "detail_movements_unlink_confirm": "Solo se quita el enlace; el movimiento no se elimina.",
      "movements_cost_centers_label": "Centros de Costo",
      "movements_cost_centers_placeholder": "Seleccioná uno o más",
      "movements_cost_centers_empty_options": "No hay Centros de Costo activos.",
      "movements_cost_centers_currency_mismatch": "La moneda del movimiento no coincide con la del CC.",
      "movements_cost_centers_inactive_hint": "Inactivo",
      "movements_cost_centers_selected_singular": "1 seleccionado",
      "movements_cost_centers_selected_plural": "{count} seleccionados",
      "feedback": {
        "cost_center_created": "Centro de Costo creado.",
        "cost_center_updated": "Centro de Costo actualizado.",
        "cost_center_closed": "Centro de Costo cerrado.",
        "cost_center_forbidden": "No tenes permisos para administrar Centros de Costo.",
        "cost_center_name_required": "El nombre es obligatorio.",
        "cost_center_type_required": "El tipo es obligatorio.",
        "cost_center_start_date_required": "La fecha de inicio es obligatoria.",
        "cost_center_currency_required": "La moneda es obligatoria.",
        "cost_center_responsible_required": "El responsable es obligatorio.",
        "cost_center_amount_required": "El monto es obligatorio para este tipo.",
        "cost_center_invalid_type": "Tipo de Centro de Costo invalido.",
        "cost_center_invalid_status": "Estado de Centro de Costo invalido.",
        "cost_center_invalid_periodicity": "Periodicidad invalida para el tipo seleccionado.",
        "cost_center_invalid_date_range": "La fecha de fin debe ser igual o posterior a la fecha de inicio.",
        "cost_center_invalid_start_date": "Fecha de inicio invalida.",
        "cost_center_invalid_end_date": "Fecha de fin invalida.",
        "cost_center_duplicate_name": "Ya existe un Centro de Costo con ese nombre.",
        "cost_center_locked_field_modified": "No se puede modificar ese campo: el CC tiene movimientos enlazados.",
        "cost_center_not_found": "Centro de Costo no encontrado.",
        "cost_center_inactive": "El Centro de Costo esta inactivo y no admite enlaces nuevos.",
        "cost_center_movement_links_synced": "Enlaces actualizados.",
        "cost_center_movement_unlinked": "Movimiento desvinculado.",
        "cost_center_unknown_error": "Ocurrio un error al procesar el Centro de Costo."
      }
    }
  },
  "consolidation": {
    "eyebrow": "Consolidacion",
    "title": "Consolidacion diaria",
    "description": "Revisa movimientos cargados por Secretaria, corrige imputaciones, integra coincidencias y consolida la fecha seleccionada.",
    "date_label": "Fecha a revisar",
    "load_cta": "Cargar fecha",
    "load_loading": "Cargando fecha...",
    "batch_label": "Fecha consolidada:",
    "batch_pending": "Pendiente",
    "batch_completed": "Consolidada",
    "batch_failed": "Fallida",
    "movements_title": "Movimientos del dia",
    "empty": "No hay movimientos de Secretaria para consolidar en la fecha seleccionada.",
    "pending_title": "Pendientes del dia",
    "integrated_title": "Movimientos integrados",
    "empty_pending": "No hay movimientos pendientes para esta fecha.",
    "empty_integrated": "No hay movimientos integrados para esta fecha.",
    "concept_label": "Concepto",
    "status_label": "Estado",
    "account_label": "Cuenta",
    "detail_label": "Detalle",
    "amount_label": "Importe",
    "actions_label": "Acciones",
    "created_by_label": "Registrado por",
    "status_pending": "Pendiente",
    "status_integrated": "Consolidado",
    "status_invalid": "Invalido",
    "status_possible_match": "Coincidencia",
    "detail_title": "Detalle del movimiento",
    "detail_description": "Revisa la imputacion completa y corrige los datos antes de consolidar si hace falta.",
    "invalid_title": "Este movimiento requiere correccion antes de consolidar.",
    "edit_cta": "Editar movimiento",
    "edit_title": "Editar movimiento de consolidacion",
    "edit_description": "Actualiza la imputacion del movimiento pendiente antes de consolidar la fecha.",
    "edit_transfer_title": "Editar transferencia de consolidacion",
    "edit_transfer_description": "Actualiza la transferencia pendiente antes de consolidar la fecha.",
    "edit_form": {
      "movement_id_label": "ID movimiento",
      "date_label": "Fecha",
      "account_label": "Cuenta",
      "account_placeholder": "Selecciona una cuenta",
      "movement_type_label": "Tipo",
      "movement_type_placeholder": "Selecciona un tipo",
      "category_label": "Sub Categoria",
      "category_placeholder": "Selecciona una sub categoria",
      "parent_category_label": "Categoria",
      "activity_label": "Actividad",
      "activity_placeholder": "Sin actividad",
      "receipt_label": "Recibo",
      "required_suffix": " *",
      "receipt_helper_example": "Ejemplo:",
      "receipt_helper_available_from": "Disponibles desde:",
      "concept_label": "Concepto",
      "currency_label": "Moneda",
      "currency_placeholder": "Selecciona una moneda",
      "amount_label": "Importe",
      "reset_cta": "Borrar formulario",
      "detail_transfer_label": "Transferencia:",
      "detail_fx_label": "Cambio de moneda:",
      "fx_source_account_label": "Cuenta origen",
      "fx_target_account_label": "Cuenta destino",
      "fx_source_currency_label": "Moneda origen",
      "fx_target_currency_label": "Moneda destino",
      "fx_source_amount_label": "Importe origen",
      "fx_target_amount_label": "Importe destino",
      "fx_source_account_placeholder": "Selecciona una cuenta origen",
      "fx_target_account_placeholder": "Selecciona una cuenta destino",
      "fx_source_currency_placeholder": "Selecciona una moneda origen",
      "fx_target_currency_placeholder": "Selecciona una moneda destino",
      "movement_types": {
        "ingreso": "Ingreso",
        "egreso": "Egreso"
      },
      "fx_create_cta": "Crear operacion",
      "fx_create_loading": "Registrando operacion..."
    },
    "save_changes_cta": "Guardar cambios",
    "save_changes_loading": "Guardando cambios...",
    "match_title": "Posible coincidencia en Tesoreria",
    "match_description": "El sistema encontro un movimiento ya cargado en Tesoreria con misma cuenta, moneda e importe.",
    "secretaria_side": "Movimiento de Secretaria",
    "tesoreria_side": "Movimiento de Tesoreria",
    "integrate_cta": "Integrar",
    "integrate_loading": "Integrando...",
    "execute_title": "Consolidar dia",
    "execute_description": "Confirma la consolidacion solo cuando todos los pendientes esten validos o ya integrados.",
    "execute_cta": "Consolidar dia",
    "execute_loading": "Consolidando...",
    "footer_total_label": "Total del dia",
    "footer_execute_cta": "Consolidar",
    "back_to_treasury_cta": "Volver a Tesoreria",
    "select_movement": "Selecciona un movimiento del listado para ver su detalle, coincidencias y auditoria.",
    "audit_actions": {
      "original": "Carga original",
      "edited": "Imputacion actualizada",
      "integrated": "Movimiento integrado",
      "consolidated": "Movimiento consolidado"
    }
  }
};
