// AUTOGENERADO desde texts.json (split-texts). NO editar a mano —
// editar lib/texts.json y regenerar con scripts/split-texts.mjs.

export const rrhh = {
  "page_title": "RRHH",
  "page_description": "Modulo de recursos humanos del club. Administra estructuras salariales, colaboradores, contratos, liquidaciones y pagos de nomina.",
  "placeholder_title": "Modulo RRHH en construccion",
  "placeholder_description": "Estamos preparando el modulo de RRHH. Muy pronto vas a poder administrar estructuras salariales, colaboradores, contratos, liquidaciones y pagos desde aca.",
  "placeholder_available_soon": "Disponible proximamente",
  "salary_structures": {
    "section_title": "Estructuras Salariales",
    "section_description": "Define las posiciones rentadas del club con su remuneración estándar.",
    "subtitle_counts": "{active} activas · {inactive} inactivas",
    "search_placeholder": "Buscar por nombre, rol o actividad",
    "create_cta": "Nueva Estructura",
    "create_full_cta": "Crear Estructura",
    "filter_all": "Todas",
    "filter_active": "Activas",
    "filter_inactive": "Inactivas",
    "filter_activity_all": "Todas las actividades",
    "col_name": "Nombre",
    "col_role": "Rol funcional",
    "col_divisions": "Divisiones",
    "col_activity": "Actividad",
    "col_payment_type": "Tipo de pago",
    "col_type": "Tipo remuneración",
    "col_amount": "Monto vigente",
    "col_status": "Estado",
    "col_contract": "Contrato vigente",
    "action_edit": "Editar",
    "action_view_detail": "Ver detalle",
    "action_update_amount": "Actualizar monto",
    "empty_title": "Sin Estructuras Salariales configuradas",
    "empty_description": "Crea la primera estructura para empezar a definir las posiciones rentadas del club.",
    "empty_cta": "Nueva Estructura",
    "empty_filter_title": "Sin resultados",
    "empty_filter_description": "Ajusta los filtros o el término de búsqueda para ver más estructuras.",
    "contract_vacant": "Vacante",
    "contract_assigned_generic": "Ocupada",
    "remuneration_type_options": {
      "mensual_fijo": "Mensual fijo",
      "por_hora": "Por hora",
      "por_clase": "Por clase"
    },
    "payment_type_options": {
      "sueldo": "Sueldo",
      "viatico": "Viático",
      "honorarios": "Honorarios"
    },
    "status_options": {
      "activa": "Activa",
      "inactiva": "Inactiva"
    },
    "create_modal_title": "Nueva Estructura Salarial",
    "create_modal_description": "Define una posición rentada con su remuneración estándar.",
    "create_submit_cta": "Crear estructura",
    "edit_modal_title": "Editar Estructura Salarial",
    "edit_modal_description": "Podés editar el nombre, tipo de remuneración, carga horaria y estado. El rol funcional, la actividad, las divisiones y el tipo de pago se manejan por separado.",
    "edit_submit_cta": "Guardar cambios",
    "amount_modal_title": "Actualizar monto",
    "amount_modal_description": "Cerra la version vigente y crea una nueva con el monto y la fecha de vigencia indicados.",
    "amount_submit_cta": "Actualizar monto",
    "amount_current_label": "Monto vigente",
    "amount_new_label": "Sueldo nuevo",
    "amount_new_placeholder": "ej. 580.000,00",
    "amount_new_helper": "Ingresa el sueldo en la moneda del club. Debe ser mayor a cero.",
    "effective_date_label": "Fecha de vigencia",
    "effective_date_helper": "Por defecto hoy. Debe ser posterior al inicio de la version vigente actual.",
    "amount_history_title": "Historial de monto",
    "amount_history_amount": "Monto",
    "amount_history_start": "Desde",
    "amount_history_end": "Hasta",
    "amount_history_current_badge": "Vigente",
    "form_name_label": "Nombre",
    "form_name_placeholder": "ej. Profesor Titular Futbol",
    "form_name_preview_label": "Nombre (generado automáticamente)",
    "form_name_preview_hint": "Se genera con Rol + División + Actividad. La combinación de rol, división y actividad debe ser única.",
    "form_role_label": "Rol funcional",
    "form_role_placeholder": "Seleccioná un rol",
    "form_divisions_label": "División / Categoría",
    "form_divisions_placeholder": "Seleccioná una o más divisiones",
    "form_divisions_helper": "Opcional. Podés elegir varias divisiones.",
    "form_activity_label": "Actividad",
    "form_activity_placeholder": "Seleccioná una actividad",
    "form_payment_type_label": "Tipo de pago",
    "form_payment_type_placeholder": "Seleccioná un tipo",
    "form_payment_type_helper": "Naturaleza contable del pago.",
    "form_remuneration_type_label": "Tipo de remuneración",
    "form_remuneration_type_placeholder": "Seleccioná un tipo",
    "form_workload_hours_label": "Carga horaria esperada",
    "form_workload_hours_placeholder": "ej. 20",
    "form_workload_hours_helper": "Opcional. Se usa como referencia para contratos por hora o por clase.",
    "form_status_label": "Estado",
    "form_status_helper": "Las estructuras inactivas no aparecen al crear contratos nuevos.",
    "form_locked_field_hint": "No editable. Para cambiar este campo, crea una nueva estructura.",
    "cancel_cta": "Cancelar",
    "submit_pending": "Guardando..."
  },
  "tab_nav": {
    "aria_label": "Sub navegacion RRHH",
    "structures": "Estructuras",
    "members": "Colaboradores",
    "contracts": "Contratos"
  },
  "module_nav": {
    "aria_label": "Navegacion del modulo RRHH",
    "resumen": "Resumen",
    "settlements": "Liquidaciones",
    "contracts": "Contratos",
    "staff": "Colaboradores",
    "structures": "Estructuras"
  },
  "home": {
    "title": "RRHH",
    "eyebrow": "Personal · Contratos · Liquidaciones",
    "description": "Estructuras, colaboradores y liquidaciones mensuales del club.",
    "settlements_eyebrow": "Operacion",
    "settlements_title": "Liquidaciones",
    "settlements_description": "Genera, ajusta, aprueba, anula y paga las liquidaciones mensuales del club activo.",
    "settlements_cta": "Ir a liquidaciones",
    "no_access_note": "Tu rol no tiene acceso a esta seccion.",
    "upcoming_sections_note": "Pronto vas a poder ejecutar pagos, revisar fichas por colaborador, consultar el dashboard y generar reportes."
  },
  "activity_detail": {
    "breadcrumb_root": "Estructuras",
    "header_eyebrow_template": "Estructura · {collaborators} colaboradores · {divisions} divisiones",
    "header_coordinator_subtitle_template": "Coordinación general: {name}",
    "cta_new_contract": "+ Contrato",
    "cta_edit_structure": "Editar",
    "edit_picker_modal_title": "Elegí una estructura",
    "edit_picker_modal_description": "Esta actividad agrupa varias estructuras. Seleccioná cuál querés editar.",
    "edit_picker_item_template": "{role} · {divisions} · {remunerationType}",
    "edit_picker_no_divisions_label": "Sin división",
    "stats_cost_eyebrow": "Costo mensual",
    "stats_cost_delta_template": "{sign}{percent}% vs {prevMonth}",
    "stats_cost_no_delta": "Sin histórico previo",
    "stats_collaborators_eyebrow": "Colaboradores",
    "stats_collaborators_subtitle_template": "{mensual} mensual · {porHora} por hora · {porClase} por clase",
    "stats_share_eyebrow": "% del total RRHH",
    "stats_share_no_data": "Sin contratos vigentes en el club",
    "collaborators_card_title_template": "Colaboradores · {activity}",
    "collaborators_card_subtitle": "Agrupados por división",
    "collaborators_group_header_template": "{division} · {count} colab.",
    "collaborators_group_amount_template": "ARS {amount} / mes",
    "collaborators_no_division_label": "Sin división",
    "collaborators_amount_unit": "/ mes",
    "empty_collaborators_title": "Sin colaboradores asignados",
    "empty_collaborators_description": "Esta actividad todavía no tiene contratos vigentes. Agregá uno desde + Contrato.",
    "cost_evolution_title": "Evolución del costo mensual",
    "cost_evolution_subtitle": "Últimos 6 meses",
    "cost_evolution_variation_label": "Variación",
    "cost_evolution_no_data": "Sin liquidaciones pagadas en los últimos 6 meses.",
    "month_short_template": "{label} {year}",
    "month_short_labels": {
      "1": "Ene",
      "2": "Feb",
      "3": "Mar",
      "4": "Abr",
      "5": "May",
      "6": "Jun",
      "7": "Jul",
      "8": "Ago",
      "9": "Sep",
      "10": "Oct",
      "11": "Nov",
      "12": "Dic"
    }
  },
  "dashboard": {
    "section_eyebrow": "Dashboard",
    "section_title": "Estado del mes",
    "alert_revisions_template": "{count} contratos no tienen revisión salarial en los últimos 12 meses.",
    "alert_revisions_cta": "Revisar",
    "settlement_status_generada": "borrador",
    "settlement_status_aprobada_rrhh": "aprobadas",
    "settlement_status_pagada": "pagadas",
    "settlement_status_anulada": "anuladas",
    "card_current_period_eyebrow": "Liquidación vigente",
    "card_current_period_title_template": "{period} · {status}",
    "card_current_period_progress_template": "{paid}/{total} pagadas · {pending} pendientes",
    "card_current_period_empty": "Sin liquidaciones generadas para el mes en curso.",
    "card_pay_this_week_eyebrow": "A pagar esta semana",
    "card_pay_this_week_title": "Pendientes de pago",
    "card_pay_this_week_subtitle_template": "{count} liquidaciones · vence {dueDateLabel}",
    "card_pay_this_week_cta": "Ver liquidaciones →",
    "card_pay_this_week_empty": "Nada pendiente de pago.",
    "card_active_staff_eyebrow": "Colaboradores activos",
    "card_active_staff_title": "Con contrato vigente",
    "card_active_staff_delta_template": "+{additions} altas en los últimos 30 días",
    "card_active_staff_delta_zero": "Sin altas en los últimos 30 días",
    "card_active_staff_cta": "Ver colaboradores →",
    "card_active_contracts_eyebrow": "Contratos vigentes",
    "card_active_contracts_title": "Total activos",
    "card_active_contracts_subtitle_template": "{revisions} con revisión atrasada · {ending} vencen en 60d",
    "card_active_contracts_subtitle_clean": "Sin revisiones atrasadas ni vencimientos próximos.",
    "card_active_contracts_cta": "Ver contratos →",
    "card_monthly_cost_eyebrow": "Costo mensual",
    "card_monthly_cost_title": "Ejecutado del mes",
    "card_monthly_cost_delta_up_template": "↑ {pct}% vs mes anterior",
    "card_monthly_cost_delta_down_template": "↓ {pct}% vs mes anterior",
    "card_monthly_cost_delta_flat": "= mismo nivel que el mes anterior",
    "card_monthly_cost_delta_none": "Sin comparable mes anterior",
    "card_monthly_cost_history_template": "{prevLabel}: {prev} · {twoLabel}: {two}",
    "card_structures_eyebrow": "Estructuras",
    "card_structures_title": "Activas en el club",
    "card_structures_more_template": "+ {count} más",
    "card_structures_cta": "Ver estructuras →",
    "card_alerts_eyebrow": "Alertas",
    "card_alerts_title": "Colaboradores sin contrato",
    "card_alerts_description": "Colaboradores que no tienen contratos vigentes.",
    "card_alerts_cta": "Ver alertas",
    "card_alerts_empty": "Sin alertas pendientes.",
    "milestones_eyebrow": "Próximos hitos",
    "milestones_title": "Revisiones salariales y vencimientos de contrato",
    "milestones_days_template": "en {days} días",
    "milestones_days_today": "hoy",
    "milestones_days_overdue_template": "vencido hace {days} días",
    "milestones_empty_title": "No hay hitos próximos",
    "milestones_empty_description": "No hay revisiones salariales atrasadas ni contratos por vencer en 60 días.",
    "milestone_type_revision": "Revisión salarial",
    "milestone_type_end_contract": "Fin de contrato"
  },
  "staff_profile": {
    "eyebrow": "Ficha",
    "alert_no_active_contracts": "Este colaborador esta activo pero no tiene contratos vigentes. Evalua reactivar un contrato o darlo de baja.",
    "activity_eyebrow": "Actividad reciente",
    "activity_empty": "Sin actividad registrada todavía.",
    "activity_actor_template": "por {name}",
    "activity_unknown_actor": "Sistema",
    "activity_actions": {
      "staff_member_created": "Colaborador creado",
      "staff_member_updated": "Datos del colaborador actualizados",
      "staff_member_bank_updated": "Datos bancarios actualizados",
      "staff_contract_created": "Nuevo contrato agregado",
      "staff_contract_finalized": "Contrato finalizado",
      "staff_contract_revision_created": "Revisión salarial aplicada",
      "payroll_settlement_generated": "Liquidación generada",
      "payroll_settlement_approved": "Liquidación aprobada por RRHH",
      "payroll_settlement_paid": "Liquidación pagada",
      "payroll_settlement_returned": "Liquidación devuelta a RRHH",
      "payroll_settlement_voided": "Liquidación anulada",
      "fallback": "Actividad registrada"
    },
    "personal_eyebrow": "Datos personales",
    "personal_title": "Datos de contacto y pago",
    "personal_email": "Email",
    "personal_phone": "Telefono",
    "personal_vinculo": "Vinculo",
    "personal_cbu": "CBU / alias",
    "personal_hire_date": "Fecha de alta",
    "contracts_title": "Contratos",
    "contracts_empty_title": "Sin contratos",
    "contracts_empty_description": "El colaborador no tiene contratos registrados todavia.",
    "contracts_col_structure": "Estructura",
    "contracts_col_start": "Desde",
    "contracts_col_end": "Hasta",
    "contracts_col_amount": "Monto",
    "contracts_col_status": "Estado",
    "settlements_title": "Liquidaciones",
    "settlements_empty_title": "Sin liquidaciones",
    "settlements_empty_description": "El colaborador no tiene liquidaciones asociadas.",
    "settlements_col_period": "Periodo",
    "settlements_col_structure": "Estructura",
    "settlements_col_total": "Monto final",
    "settlements_col_status": "Estado",
    "settlements_col_paid_at": "Pagado el",
    "payments_title": "Pagos",
    "payments_empty_title": "Sin pagos",
    "payments_empty_description": "Todavia no se ejecutaron pagos para este colaborador.",
    "payments_col_date": "Fecha",
    "payments_col_movement": "Movimiento",
    "payments_col_account": "Cuenta",
    "payments_col_amount": "Monto",
    "back_to_masters": "Volver a maestros",
    "breadcrumb_root": "Colaboradores",
    "header_alta_template": "Colaborador · Alta {date}",
    "edit_cta": "Editar datos",
    "new_contract_cta": "+ Nuevo contrato",
    "edit_modal_title": "Editar colaborador",
    "edit_modal_description": "Actualizá los datos del colaborador sin afectar sus contratos vigentes.",
    "edit_submit_cta": "Guardar cambios",
    "edit_cancel_cta": "Cancelar",
    "edit_pending": "Guardando…",
    "info_title": "Datos personales",
    "info_description": "Datos identificatorios y de contacto.",
    "info_fullname_label": "NOMBRE COMPLETO",
    "info_dni_label": "DNI",
    "info_cuil_label": "CUIT/CUIL",
    "info_vinculo_label": "TIPO DE VÍNCULO",
    "info_hire_date_label": "FECHA DE ALTA",
    "info_value_fallback": "—",
    "contact_title": "Contacto",
    "contact_description": "Email y teléfono para notificaciones.",
    "contact_email_label": "EMAIL",
    "contact_phone_label": "TELÉFONO",
    "bank_title": "Datos bancarios",
    "bank_description": "Para pago de liquidaciones.",
    "bank_cbu_label": "CBU / ALIAS",
    "tenure_eyebrow": "ANTIGÜEDAD EN EL CLUB",
    "tenure_years_singular": "año",
    "tenure_years_plural": "años",
    "tenure_months_singular": "mes",
    "tenure_months_plural": "meses",
    "tenure_zero": "Menos de un mes",
    "tenure_since_template": "Alta {date}",
    "contracts_new_cta": "+ Nuevo",
    "contracts_item_title_template": "{code} · {role} · {structure}",
    "contracts_item_role_fallback": "Sin rol",
    "contracts_item_structure_fallback": "Sin estructura",
    "contracts_item_since_template": "Desde {from}",
    "contracts_item_range_template": "Desde {from} · Hasta {to}",
    "contracts_amount_unit_mensual_fijo": "/ mes",
    "contracts_amount_unit_por_hora": "/ hora",
    "contracts_amount_unit_por_clase": "/ clase",
    "new_contract_modal_title": "Nuevo contrato",
    "new_contract_modal_description": "Asocia al colaborador con una Estructura Salarial disponible."
  },
  "settlements": {
    "page_eyebrow": "RRHH",
    "page_title": "Liquidaciones",
    "page_description": "Genera, ajusta, aprueba y anula las liquidaciones mensuales de los contratos vigentes.",
    "subtitle_counts": "{generada} generadas · {aprobada_rrhh} aprobadas · {pagada} pagadas · {anulada} anuladas",
    "search_placeholder": "Buscar por colaborador, estructura o periodo",
    "generate_cta": "Generar liquidaciones",
    "generate_modal_title": "Generar liquidaciones del mes",
    "generate_modal_description": "Crea una liquidacion por cada contrato vigente durante el periodo seleccionado. Ignora los contratos que ya tienen liquidacion no anulada.",
    "generate_month_label": "Mes",
    "generate_year_label": "Anio",
    "generate_helper": "Por defecto se propone el mes en curso. Se puede elegir un mes pasado si queda algun ajuste pendiente.",
    "generate_submit_cta": "Generar",
    "filter_all": "Todas",
    "filter_generada": "Generadas",
    "filter_aprobada_rrhh": "Aprobadas RRHH",
    "filter_pagada": "Pagadas",
    "filter_anulada": "Anuladas",
    "filter_period_all": "Todos los periodos",
    "period_picker_aria_prev": "Periodo anterior",
    "period_picker_aria_next": "Periodo siguiente",
    "period_empty_title_template": "Sin liquidaciones para {period}",
    "period_empty_description": "Genera las liquidaciones del periodo seleccionado o navega a otro mes.",
    "col_period": "Periodo",
    "col_member": "Colaborador",
    "col_structure": "Estructura",
    "col_base": "Monto base",
    "col_total": "Monto final",
    "col_status": "Estado",
    "status_options": {
      "generada": "Generada",
      "aprobada_rrhh": "Aprobada RRHH",
      "pagada": "Pagada",
      "anulada": "Anulada"
    },
    "requires_hours_badge": "Cargar horas",
    "action_detail": "Detalle",
    "action_approve": "Aprobar",
    "action_pay": "Pagar",
    "action_return": "Devolver a generada",
    "action_annul": "Anular",
    "action_annul_paid_tooltip": "Requiere reversion previa del movimiento de Tesoreria",
    "select_all_label": "Seleccionar todas",
    "select_row_label": "Seleccionar liquidacion",
    "bulk_selected_prefix": "Seleccionadas: ",
    "bulk_clear_cta": "Limpiar",
    "bulk_approve_cta": "Aprobar seleccionadas",
    "bulk_pay_cta": "Pagar seleccionadas",
    "bulk_mixed_note": "Mezclando estados; elegi solo generadas o solo aprobadas.",
    "bulk_modal_title": "Aprobar liquidaciones",
    "bulk_modal_description": "Revisa el resumen antes de aprobar. Las liquidaciones con monto final cero requieren confirmacion explicita.",
    "bulk_summary_count": "Cantidad",
    "bulk_summary_total": "Monto total",
    "bulk_approve_zero_label": "Aprobar liquidaciones con total cero",
    "bulk_approve_zero_description": "Algunas liquidaciones tienen monto final en cero. Marcalo para aprobarlas igualmente.",
    "bulk_submit_cta": "Aprobar",
    "approve_modal_title": "Aprobar liquidacion",
    "approve_zero_warning": "El monto final es cero. Al aprobar la liquidacion quedara bloqueada para edicion.",
    "approve_submit_cta": "Aprobar",
    "return_modal_title": "Devolver liquidacion a generada",
    "return_modal_description": "La liquidacion vuelve a estado generada y queda editable. Indica el motivo para registrarlo en el historial.",
    "return_reason_label": "Motivo de la devolucion",
    "return_reason_placeholder": "Ej. error en horas cargadas; ajuste pendiente; cuenta de pago incorrecta...",
    "return_submit_cta": "Devolver a generada",
    "returned_by_template": "Devuelta por {role}",
    "returned_role_options": {
      "rrhh": "RRHH",
      "tesoreria": "Tesoreria"
    },
    "pay_modal_title": "Pagar liquidacion",
    "pay_modal_description": "Al confirmar se genera un movimiento de egreso en Tesoreria con categoria Sueldos y la liquidacion pasa a pagada. Solo se puede pagar una liquidacion en estado aprobada por RRHH.",
    "pay_amount_label": "Monto a pagar",
    "pay_account_label": "Cuenta de origen",
    "pay_account_placeholder": "Selecciona una cuenta",
    "pay_account_helper": "Solo aparecen cuentas de Tesoreria habilitadas que soportan la moneda del club.",
    "pay_date_label": "Fecha de pago",
    "pay_receipt_label": "Comprobante",
    "pay_receipt_placeholder": "Opcional",
    "pay_notes_label": "Notas",
    "pay_notes_placeholder": "Observaciones opcionales del tesorero.",
    "pay_submit_cta": "Confirmar pago",
    "pay_bulk_modal_title": "Pagar liquidaciones en lote",
    "pay_bulk_modal_description": "Cada liquidacion seleccionada genera un movimiento en Tesoreria. Si alguna falla, se revierte todo el lote.",
    "pay_bulk_submit_cta": "Confirmar pagos",
    "pay_bulk_notes_label": "Notas comunes",
    "pay_bulk_notes_helper": "Se aplican a cada movimiento generado.",
    "pay_bulk_warning": "Si alguna liquidacion falla durante el proceso, ninguna se marca como pagada y no se crean movimientos.",
    "annul_modal_title": "Anular liquidacion",
    "annul_modal_description": "Al anular la liquidacion queda fuera de los reportes y puede regenerarse el periodo.",
    "annul_warning": "Esta accion registra la anulacion en el historial. La liquidacion queda visible como anulada.",
    "annul_paid_warning": "Para anular una liquidacion pagada primero debes revertir el movimiento de Tesoreria asociado.",
    "annul_submit_cta": "Anular liquidacion",
    "detail_modal_title": "Detalle de liquidacion",
    "detail_modal_description": "Cargar horas, agregar ajustes y editar notas.",
    "adjustments_section_title": "Ajustes",
    "adjustments_total_label": "Total ajustes",
    "adjustments_col_type": "Tipo",
    "adjustments_col_concept": "Concepto",
    "adjustments_col_amount": "Monto",
    "adjustments_empty": "Sin ajustes cargados.",
    "adjustment_type_options": {
      "adicional": "Adicional",
      "descuento": "Descuento",
      "reintegro": "Reintegro"
    },
    "adjustment_add_cta": "Agregar ajuste",
    "adjustment_delete_cta": "Eliminar ajuste",
    "hours_worked_label": "Horas trabajadas",
    "classes_worked_label": "Clases dictadas",
    "hours_helper": "El monto base se recalcula al guardar multiplicando por el valor unitario del contrato.",
    "save_hours_cta": "Guardar horas",
    "notes_label": "Notas",
    "notes_placeholder": "Observaciones opcionales del tesorero.",
    "save_notes_cta": "Guardar notas",
    "close_cta": "Cerrar",
    "form_reason_label": "Motivo (opcional)",
    "form_reason_placeholder": "Ej. se regenera en la proxima corrida, error de datos...",
    "empty_title": "Sin liquidaciones",
    "empty_description": "Genera las liquidaciones del mes para los contratos vigentes.",
    "empty_cta": "Generar liquidaciones",
    "empty_filter_title": "Sin resultados",
    "empty_filter_description": "Ajusta los filtros para ver mas liquidaciones.",
    "cancel_cta": "Cancelar",
    "submit_pending": "Guardando...",
    "feedback": {
      "settlement_generated": "Las liquidaciones del periodo se generaron correctamente.",
      "settlement_approved": "La liquidacion se aprobo correctamente.",
      "settlement_approved_bulk": "Las liquidaciones seleccionadas se aprobaron correctamente.",
      "settlement_returned_to_generated": "La liquidacion volvio a estado generada y quedo editable.",
      "settlement_annulled": "La liquidacion se anulo correctamente.",
      "settlement_adjustment_added": "El ajuste se agrego correctamente.",
      "settlement_adjustment_updated": "El ajuste se actualizo correctamente.",
      "settlement_adjustment_removed": "El ajuste se elimino correctamente.",
      "settlement_hours_loaded": "Las horas se actualizaron y el monto base se recalculo.",
      "settlement_base_amount_updated": "El monto base se actualizo correctamente.",
      "settlement_notes_updated": "Las notas se guardaron correctamente.",
      "settlement_partial": "Se proceso una parte de la operacion. Revisa el detalle.",
      "settlement_not_found": "No encontramos la liquidacion seleccionada.",
      "settlement_adjustment_not_found": "No encontramos el ajuste seleccionado.",
      "settlement_invalid_period": "El periodo seleccionado no es valido.",
      "settlement_no_active_contracts": "No hay contratos vigentes para generar liquidaciones en ese periodo.",
      "settlement_invalid_type": "El tipo de ajuste seleccionado no es valido.",
      "settlement_concept_required": "Debes completar el concepto del ajuste.",
      "settlement_amount_required": "Debes completar el monto del ajuste.",
      "settlement_amount_must_be_positive": "El monto del ajuste debe ser mayor a cero.",
      "settlement_hours_required": "Debes cargar horas o clases antes de aprobar.",
      "settlement_classes_required": "La cantidad de clases debe ser valida.",
      "settlement_edit_blocked_approved": "La liquidacion esta aprobada por RRHH y no admite edicion.",
      "settlement_edit_blocked_paid": "La liquidacion esta pagada y no admite edicion.",
      "settlement_edit_blocked_annulled": "La liquidacion esta anulada y no admite edicion.",
      "settlement_total_negative": "El monto final no puede ser negativo. Revisa los ajustes.",
      "settlement_zero_amount_requires_approval": "El monto final es cero y requiere confirmacion explicita.",
      "settlement_invalid_status": "El estado actual de la liquidacion no permite esta operacion.",
      "settlement_already_approved": "La liquidacion ya esta aprobada por RRHH.",
      "settlement_reason_required": "Debes indicar el motivo de la devolucion.",
      "settlement_already_annulled": "La liquidacion ya fue anulada.",
      "settlement_movement_still_active": "Antes de anular una liquidacion pagada, debes revertir el movimiento de Tesoreria asociado.",
      "settlement_forbidden": "No tienes permisos para operar liquidaciones.",
      "settlement_unknown_error": "No pudimos completar la operacion sobre la liquidacion. Vuelve a intentarlo.",
      "settlement_paid": "La liquidacion se pago correctamente y el movimiento quedo registrado en Tesoreria.",
      "settlement_paid_batch": "El pago en lote se proceso correctamente.",
      "settlement_payment_account_required": "Debes seleccionar una cuenta de origen.",
      "settlement_payment_account_not_available": "La cuenta seleccionada no esta disponible para Tesoreria en el club activo.",
      "settlement_payment_currency_mismatch": "La cuenta no admite la moneda del club.",
      "settlement_payment_date_required": "Debes completar la fecha de pago.",
      "settlement_payment_invalid_date": "La fecha de pago debe estar entre los ultimos 365 dias y los proximos 7 dias.",
      "settlement_payment_already_paid": "La liquidacion ya fue pagada.",
      "settlement_payment_invalid_total": "El monto final debe ser mayor a cero para poder pagar.",
      "settlement_payment_sueldos_category_missing": "El club no tiene configurada la categoria Sueldos. Regenera categorias desde Configuracion antes de reintentar.",
      "settlement_payment_club_not_found": "No encontramos el club activo.",
      "settlement_payment_display_ids_mismatch": "Error interno al generar los numeros de movimiento. Reintenta.",
      "settlement_payment_partial_failure": "Hubo un error parcial procesando el lote. Ninguna liquidacion quedo pagada."
    }
  },
  "staff_members": {
    "section_title": "Colaboradores",
    "section_description": "Maestro de personas rentadas del club. Mantiene datos personales, vínculo y datos de pago.",
    "subtitle_counts": "{total} colaboradores",
    "search_placeholder": "Buscar por nombre, DNI o CUIT",
    "create_cta": "Nuevo colaborador",
    "filter_with_active": "Con contrato vigente",
    "filter_all": "Todos",
    "filter_without_active": "Sin contratos",
    "filter_vinculo_all": "Todos los vínculos",
    "col_name": "Nombre",
    "col_dni": "DNI",
    "col_cuit": "CUIT/CUIL",
    "col_vinculo": "Vínculo",
    "col_contracts": "Vigentes",
    "action_edit": "Editar",
    "action_view_detail": "Ver ficha",
    "alert_no_active_contracts": "Sin contratos vigentes",
    "alert_banner_singular": "colaborador sin contratos vigentes. Creá un contrato nuevo para habilitar liquidaciones.",
    "alert_banner_plural": "colaboradores sin contratos vigentes. Creá contratos nuevos para habilitar liquidaciones.",
    "alert_banner_cta_only": "Ver solo alertas",
    "alert_banner_cta_all": "Ver todos",
    "vinculo_options": {
      "relacion_dependencia": "Relación de dependencia",
      "monotributista": "Monotributista",
      "honorarios": "Honorarios",
      "contrato_locacion": "Contrato de locación"
    },
    "empty_title": "Sin colaboradores configurados",
    "empty_description": "Cargue los colaboradores rentados del club para poder generar contratos.",
    "empty_cta": "Nuevo colaborador",
    "empty_filter_title": "Sin resultados",
    "empty_filter_description": "Ajustá los filtros o el término de búsqueda.",
    "create_modal_title": "Nuevo colaborador",
    "create_modal_description": "Cargá los datos personales, el vínculo y los datos de pago del colaborador.",
    "create_submit_cta": "Crear colaborador",
    "edit_modal_title": "Editar colaborador",
    "edit_modal_description": "Actualizá los datos del colaborador sin afectar sus contratos vigentes.",
    "edit_submit_cta": "Guardar cambios",
    "form_first_name_label": "Nombre",
    "form_last_name_label": "Apellido",
    "form_dni_label": "DNI",
    "form_dni_helper": "Ingresa 7 u 8 digitos sin puntos.",
    "form_cuit_label": "CUIT/CUIL",
    "form_cuit_placeholder": "20-12345678-9",
    "form_cuit_helper": "Formato XX-XXXXXXXX-X con digito verificador valido.",
    "form_email_label": "Email",
    "form_email_placeholder": "opcional",
    "form_phone_label": "Telefono",
    "form_phone_placeholder": "+54 221 425-8100",
    "form_vinculo_label": "Tipo de vínculo",
    "form_vinculo_placeholder": "Selecciona un vinculo",
    "form_cbu_label": "CBU o alias",
    "form_cbu_placeholder": "opcional",
    "form_hire_date_label": "Fecha de alta",
    "cancel_cta": "Cancelar",
    "submit_pending": "Guardando..."
  },
  "staff_contracts": {
    "section_title": "Contratos",
    "section_description": "Vínculos rentados activos y finalizados. Cada contrato une un colaborador con una Estructura Salarial.",
    "subtitle_counts": "{vigente} vigentes · {finalizado} finalizados",
    "search_placeholder": "Buscar por colaborador o estructura",
    "create_cta": "Nuevo contrato",
    "create_full_cta": "Crear contrato",
    "bulk_revision_cta": "Revisión masiva",
    "filter_all": "Todos",
    "filter_vigente": "Vigentes",
    "filter_finalizado": "Finalizados",
    "col_member": "Colaborador",
    "col_structure": "Estructura",
    "col_start": "Desde",
    "col_end": "Hasta",
    "col_amount_mode": "Monto",
    "col_amount": "Monto vigente",
    "col_status": "Estado",
    "amount_mode_structure": "De la estructura",
    "amount_mode_frozen": "Congelado",
    "status_options": {
      "vigente": "Vigente",
      "finalizado": "Finalizado"
    },
    "unknown_member": "Colaborador",
    "unknown_structure": "Estructura",
    "action_edit": "Editar",
    "action_view_detail": "Ver ficha",
    "action_finalize": "Finalizar",
    "empty_title": "Sin contratos",
    "empty_description": "Crea el primer contrato asociando un colaborador con una Estructura Salarial.",
    "empty_cta": "Nuevo contrato",
    "empty_filter_title": "Sin resultados",
    "empty_filter_description": "Ajusta el filtro para ver mas contratos.",
    "create_modal_title": "Nuevo contrato",
    "create_modal_description": "Asocia un colaborador activo con una Estructura Salarial disponible.",
    "create_submit_cta": "Crear contrato",
    "edit_modal_title": "Editar contrato",
    "edit_modal_description": "Podes editar la fecha de fin, el modo de calculo del monto y el monto congelado.",
    "edit_submit_cta": "Guardar cambios",
    "finalize_modal_title": "Finalizar contrato",
    "finalize_modal_description": "Al finalizar, la estructura queda libre para un contrato nuevo y se bloquea la generacion de liquidaciones posteriores.",
    "finalize_warning": "Esta accion es irreversible. Si cambian las condiciones y el vinculo se renueva, hay que crear un contrato nuevo.",
    "finalize_submit_cta": "Finalizar contrato",
    "finalize_end_date_helper": "Por defecto hoy. Debe ser mayor o igual a la fecha de inicio del contrato.",
    "form_member_label": "Colaborador",
    "form_member_placeholder": "Selecciona un colaborador",
    "form_member_helper": "Solo aparecen colaboradores activos.",
    "form_structure_label": "Estructura Salarial",
    "form_structure_placeholder": "Selecciona una estructura",
    "form_structure_helper": "Solo aparecen estructuras activas sin contrato vigente.",
    "form_start_date_label": "Fecha de inicio",
    "form_start_date_helper": "Por defecto hoy. Se admiten hasta 30 dias retroactivos.",
    "form_end_date_label": "Fecha de fin",
    "form_end_date_helper": "Opcional. Podes dejarlo vacio para contratos por tiempo indeterminado.",
    "form_initial_amount_label": "Monto inicial",
    "form_initial_amount_placeholder": "ej. 500.000,00",
    "form_initial_amount_helper": "Queda registrado como la primera revisión salarial del contrato.",
    "form_currency_label": "Moneda",
    "form_currency_helper": "Moneda del club (no editable).",
    "form_initial_revision_reason_label": "Motivo de la revisión inicial",
    "form_initial_revision_reason_placeholder": "Monto inicial del contrato",
    "form_initial_revision_reason_helper": "Opcional. Si lo dejás vacío se guarda 'Monto inicial del contrato'.",
    "form_reason_label": "Motivo (opcional)",
    "form_reason_placeholder": "Ej. renuncia, fin de temporada, cambio de rol...",
    "form_locked_field_hint": "No editable. Para cambiar este campo, finaliza el contrato y crea uno nuevo.",
    "cancel_cta": "Cancelar",
    "submit_pending": "Guardando..."
  },
  "bulk_revision": {
    "back_cta": "← Volver a contratos",
    "title": "Revisión salarial masiva",
    "description": "Aplica un ajuste (porcentaje, monto fijo o monto definido) sobre varios contratos vigentes en una sola operación. Si alguno falla, la operación se revierte completa.",
    "filters_eyebrow": "FILTROS",
    "filters_title": "Filtrar contratos candidatos",
    "filter_role_label": "Rol funcional",
    "filter_role_all": "Todos los roles",
    "filter_activity_label": "Actividad",
    "filter_activity_all": "Todas las actividades",
    "filter_structure_label": "Estructura",
    "filter_structure_all": "Todas las estructuras",
    "selection_eyebrow": "SELECCIÓN",
    "selection_title": "Contratos seleccionados: {count}",
    "select_all_cta": "Seleccionar todos",
    "deselect_all_cta": "Deseleccionar todos",
    "empty_title": "Sin contratos vigentes",
    "empty_description": "Ajustá los filtros o creá contratos para ver resultados.",
    "col_member": "Colaborador",
    "col_structure": "Estructura",
    "col_current": "Monto actual",
    "col_preview": "Monto resultante",
    "adjust_eyebrow": "AJUSTE",
    "adjust_title": "Configuración del aumento",
    "form_adjustment_type_label": "Tipo de ajuste",
    "form_adjustment_type_helper": "Porcentaje, monto fijo a sumar, o fijar el monto exacto.",
    "adjustment_type_options": {
      "percent": "Aumentar porcentaje (%)",
      "fixed": "Aumentar monto fijo",
      "set": "Fijar monto"
    },
    "form_value_label": "Valor",
    "form_value_placeholder_percent": "ej. 10",
    "form_value_placeholder_amount": "ej. 50.000,00",
    "form_value_helper_percent": "Porcentaje de aumento. Admite negativos para reducciones.",
    "form_value_helper_amount": "Monto en {currency}. Admite negativos en 'monto fijo'.",
    "form_effective_date_label": "Fecha de vigencia",
    "form_effective_date_helper": "Debe ser posterior a la revisión anterior de cada contrato.",
    "form_reason_label": "Motivo",
    "form_reason_placeholder": "ej. Aumento paritario semestral",
    "form_reason_helper": "Obligatorio. Queda registrado en cada revisión creada.",
    "submit_cta": "Aplicar revisión masiva",
    "submit_pending": "Aplicando..."
  },
  "contract_detail": {
    "back_cta": "← Volver a contratos",
    "back_to_list": "Volver al listado",
    "card_start_eyebrow": "DESDE",
    "card_end_eyebrow": "HASTA",
    "card_end_indefinite": "Sin fecha fin",
    "card_current_amount_eyebrow": "MONTO VIGENTE",
    "new_revision_cta": "Nueva revisión",
    "revisions_eyebrow": "HISTORIAL",
    "revisions_title": "Revisiones salariales",
    "revisions_description": "Cada revisión guarda el monto vigente, la fecha de vigencia y el motivo. Solo una revisión puede estar abierta a la vez.",
    "revisions_empty_title": "Sin revisiones registradas",
    "revisions_empty_description": "Este contrato no tiene revisiones aún.",
    "col_effective_from": "Desde",
    "col_effective_to": "Hasta",
    "col_reason": "Motivo",
    "col_amount": "Monto",
    "col_revision_status": "Estado",
    "revision_current_badge": "Vigente",
    "revision_closed_badge": "Cerrada",
    "new_revision_modal_title": "Nueva revisión salarial",
    "new_revision_modal_description": "Se cierra la revisión vigente y se abre una nueva con la fecha de vigencia indicada.",
    "new_revision_submit_cta": "Crear revisión",
    "form_amount_label": "Monto nuevo",
    "form_amount_placeholder": "ej. 680.000,00",
    "form_amount_helper": "Monto en {currency}. Debe ser mayor a cero.",
    "revision_context_template": "{staff} · {role}{activitySeparator}{activity}",
    "revision_preview_current_label": "MONTO VIGENTE",
    "revision_preview_new_label": "NUEVO MONTO",
    "revision_preview_new_placeholder": "—",
    "revision_calc_mode_label": "Cómo calcular",
    "revision_calc_mode_percent": "% variación",
    "revision_calc_mode_amount": "Monto nuevo",
    "revision_percent_label": "Variación (%)",
    "revision_percent_placeholder": "ej. 12,50",
    "revision_percent_helper": "El monto nuevo se calcula automáticamente.",
    "revision_motivo_label": "Motivo",
    "revision_motivo_placeholder": "Seleccioná un motivo",
    "revision_motivo_other": "Otro (detallar en observaciones)",
    "revision_motivo_options": {
      "paritaria": "Paritaria",
      "trimestral": "Actualización trimestral programada",
      "inflacion": "Ajuste por inflación",
      "promocion": "Promoción / cambio de rol",
      "correccion": "Corrección de monto"
    },
    "revision_observations_label": "Observaciones",
    "revision_observations_placeholder": "Contexto interno de la revisión…",
    "revision_observations_helper": "Opcional. Se guarda junto al motivo para auditoría.",
    "form_effective_date_label": "Fecha de vigencia",
    "form_effective_date_helper": "Debe ser posterior a la vigencia de la revisión anterior.",
    "form_reason_label": "Motivo (opcional)",
    "form_reason_placeholder": "Ej. aumento paritario semestral",
    "cancel_cta": "Cancelar",
    "submit_pending": "Guardando...",
    "attachments_eyebrow": "ADJUNTOS",
    "attachments_title": "Documentos del contrato",
    "attachments_description": "PDF, Word o imágenes (máx. 10 MB).",
    "attachments_empty_title": "Sin adjuntos",
    "attachments_empty_description": "Este contrato no tiene documentos cargados todavía.",
    "upload_cta": "Subir",
    "upload_pending": "Subiendo...",
    "download_cta": "Descargar",
    "delete_cta": "Eliminar",
    "breadcrumb_root": "Contratos",
    "header_vigente_since_template": "Contrato {code} · Vigente desde {date}",
    "header_finalizado_since_template": "Contrato {code} · Finalizado el {date}",
    "view_staff_profile_cta": "Ver ficha colaborador",
    "finalize_contract_cta": "Finalizar contrato",
    "new_revision_cta_plus": "+ Nueva revisión",
    "finalize_modal_title": "Finalizar contrato",
    "finalize_modal_description": "Al finalizar, el contrato pasa a estado Finalizado y se cierra la revisión salarial vigente.",
    "finalize_modal_submit_cta": "Finalizar",
    "finalize_warning": "Esta acción es irreversible. Confirmá la fecha de fin y el motivo.",
    "finalize_end_date_label": "Fecha de fin",
    "finalize_end_date_helper": "Cierra el contrato y su revisión vigente con esta fecha.",
    "finalize_reason_label": "Motivo (opcional)",
    "finalize_reason_placeholder": "Ej. fin de temporada",
    "info_title": "Información del contrato",
    "info_description": "Datos generales del contrato.",
    "info_number_label": "NÚMERO",
    "info_payment_type_label": "TIPO",
    "info_structure_label": "ESTRUCTURA",
    "info_division_label": "DIVISIÓN",
    "info_role_label": "ROL",
    "info_remuneration_type_label": "TIPO DE REMUNERACIÓN",
    "info_activity_label": "ACTIVIDAD",
    "info_start_label": "INICIO",
    "info_end_label": "FINALIZACIÓN",
    "info_end_indefinite": "Indeterminado",
    "info_value_fallback": "—",
    "history_title": "Historial de revisiones",
    "history_last_change_template": "Último cambio: {date} · {deltaPercent}",
    "history_last_change_initial": "Revisión inicial del contrato",
    "history_new_cta": "+ Nueva",
    "history_current_badge": "Actual",
    "history_initial_tag": "Inicial",
    "history_percent_vs_previous_template": "{deltaPercent} vs anterior",
    "history_range_template": "{from} → {to}",
    "history_range_open_template": "{from} → actual",
    "history_empty_title": "Sin revisiones",
    "history_empty_description": "Este contrato no tiene revisiones registradas.",
    "current_amount_eyebrow_template": "MONTO VIGENTE · {paymentType}",
    "current_amount_reviewed_on_template": "Revisado el {date}",
    "current_amount_reviewed_with_delta_template": "Revisado el {date} · {deltaPercent} vs anterior",
    "current_amount_empty": "Sin monto vigente",
    "documents_title": "Documentos",
    "documents_description": "PDF, Word o imágenes (máx. 10 MB).",
    "documents_empty_title": "Sin documentos",
    "documents_empty_description": "Este contrato no tiene documentos cargados todavía.",
    "settlements_title": "Últimas liquidaciones",
    "settlements_description": "Asociadas a este contrato.",
    "settlements_see_all_cta": "Ver todas",
    "settlements_empty_title": "Sin liquidaciones",
    "settlements_empty_description": "Todavía no se generaron liquidaciones para este contrato.",
    "settlements_period_template": "{month} {year}",
    "settlements_status_generada": "Pendiente",
    "settlements_status_aprobada_rrhh": "Aprobada RRHH",
    "settlements_status_pagada": "Pagada",
    "settlements_status_anulada": "Anulada"
  }
};
