// AUTOGENERADO desde texts.json (split-texts). NO editar a mano —
// editar lib/texts.json y regenerar con scripts/split-texts.mjs.

export const settings = {
  "club": {
    "eyebrow": "Club · Admin",
    "title": "Configuración",
    "description": "Ajustes del club, usuarios, roles y operativa.",
    "forbidden_title": "No tienes permisos para abrir esta configuracion",
    "forbidden_description": "Solo un usuario con rol Admin del club activo puede acceder a esta pagina.",
    "back_to_dashboard_cta": "Volver al dashboard",
    "club_summary_title": "Club activo",
    "club_summary_description": "Identidad institucional y visual del club. Los cambios se reflejan en el header y en toda la aplicacion.",
    "club_summary_status_label": "Contexto",
    "club_summary_status_value": "Club operativo",
    "club_summary_roles_empty": "Sin roles operativos visibles",
    "tabs": {
      "club_data": "Datos",
      "journey": "Jornada",
      "categories_activities": "Categorías",
      "members": "Usuarios",
      "role_permissions": "Permisos",
      "receipt_numbering": "Numeración",
      "notifications": "Notificaciones",
      "integrations": "Integraciones",
      "audit": "Auditoría",
      "membership_systems": "Socios"
    },
    "placeholders": {
      "coming_soon_badge": "Próximamente",
      "journey": {
        "eyebrow": "Jornada",
        "title": "Configuración de la jornada operativa",
        "description": "Definí los parámetros de apertura, cierre y horarios de la jornada. Esta sección estará disponible en una próxima iteración."
      },
      "role_permissions": {
        "eyebrow": "Permisos por rol",
        "title": "Matriz de permisos por rol",
        "description": "Ajustá qué puede hacer cada rol dentro del club. Esta sección estará disponible en una próxima iteración."
      },
      "receipt_numbering": {
        "eyebrow": "Numeración de comprobantes",
        "title": "Reglas de numeración de comprobantes",
        "description": "Definí prefijos, series y correlatividad para los comprobantes del club. Esta sección estará disponible en una próxima iteración."
      },
      "notifications": {
        "eyebrow": "Notificaciones",
        "title": "Notificaciones del club",
        "description": "Configurá los eventos que disparan avisos a miembros y al equipo operativo. Esta sección estará disponible en una próxima iteración."
      },
      "integrations": {
        "eyebrow": "Integraciones",
        "title": "Integraciones con servicios externos",
        "description": "Conectá el club con pasarelas de pago, calendarios y otros sistemas. Esta sección estará disponible en una próxima iteración."
      },
      "audit": {
        "eyebrow": "Auditoría",
        "title": "Registro de auditoría",
        "description": "Consultá el historial de cambios sensibles de la configuración del club. Esta sección estará disponible en una próxima iteración."
      }
    },
    "identity": {
      "section_title": "Identidad",
      "section_description": "Datos institucionales del club. Se usan en el header, comprobantes y comunicaciones.",
      "name_label": "Nombre del club",
      "name_placeholder": "ej. Club Atletico Primera Junta",
      "cuit_label": "CUIT",
      "cuit_placeholder": "30-12345678-9",
      "cuit_helper": "Formato: XX-XXXXXXXX-X",
      "tipo_label": "Tipo",
      "tipo_placeholder": "Selecciona un tipo",
      "tipo_options": {
        "asociacion_civil": "Asociacion civil",
        "fundacion": "Fundacion",
        "sociedad_civil": "Sociedad civil"
      },
      "currency_label": "Moneda del club",
      "currency_placeholder": "Selecciona una moneda",
      "currency_helper": "Moneda por defecto del club. Se usa en modulos que requieren una unidad monetaria canonica (ej. Estructuras Salariales).",
      "currency_options": {
        "ARS": "Peso argentino (ARS)",
        "USD": "Dolar estadounidense (USD)"
      },
      "domicilio_label": "Domicilio",
      "domicilio_placeholder": "Calle, numero, ciudad",
      "email_label": "Email de contacto",
      "email_placeholder": "contacto@club.com",
      "telefono_label": "Telefono",
      "telefono_placeholder": "+54 221 425-8100",
      "telefono_helper": "Incluye el codigo de pais (ej. +54).",
      "logo_label": "Logo del club",
      "logo_description": "PNG o SVG. Minimo 256x256 px. Maximo 2 MB. Fondo transparente recomendado.",
      "logo_upload_cta": "Subir nuevo logo",
      "logo_remove_cta": "Quitar logo",
      "logo_replace_cta": "Reemplazar logo",
      "colors_section_title": "Colores identificatorios",
      "colors_section_description": "Define la paleta institucional del club. Se usara para acentos visuales.",
      "color_primary_label": "Color primario",
      "color_secondary_label": "Color secundario",
      "color_preview_label": "Vista previa",
      "save_cta": "Guardar cambios",
      "save_loading": "Guardando...",
      "cancel_cta": "Cancelar",
      "feedback": {
        "club_identity_updated": "Los datos del club se actualizaron correctamente.",
        "invalid_name": "El nombre del club debe tener al menos 2 caracteres.",
        "invalid_cuit": "Revisa el formato del CUIT (XX-XXXXXXXX-X).",
        "invalid_cuit_dv": "El CUIT ingresado no es valido.",
        "invalid_tipo": "El tipo seleccionado no es valido.",
        "invalid_domicilio": "El domicilio debe tener entre 4 y 200 caracteres.",
        "invalid_email": "El email ingresado no es valido.",
        "invalid_telefono": "El formato del telefono no es valido.",
        "invalid_telefono_missing_prefix": "El telefono debe incluir el codigo de pais (ej. +54).",
        "invalid_color": "Los colores deben ser codigos hexadecimales validos (ej. #0EA5E9).",
        "invalid_currency": "La moneda seleccionada no es valida.",
        "invalid_logo": "El logo debe ser PNG o SVG y pesar menos de 2 MB.",
        "invalid_logo_dimensions": "El logo debe tener al menos 256x256 pixeles.",
        "logo_upload_failed": "No pudimos subir el logo. Vuelve a intentarlo.",
        "logo_optimization_failed": "No pudimos procesar el logo. Verifica el archivo y vuelve a intentarlo.",
        "club_not_found": "No encontramos el club activo. Vuelve a ingresar.",
        "forbidden": "No tienes permisos para editar los datos del club.",
        "unknown_error": "No pudimos guardar los cambios. Vuelve a intentarlo."
      }
    },
    "rrhh": {
      "feedback": {
        "salary_structure_created": "La Estructura Salarial se creo correctamente.",
        "salary_structure_updated": "La Estructura Salarial se actualizo correctamente.",
        "salary_structure_status_changed": "El estado de la Estructura Salarial se actualizo.",
        "salary_structure_not_found": "No encontramos la Estructura Salarial seleccionada.",
        "salary_structure_name_required": "Debes completar el nombre de la estructura.",
        "salary_structure_role_required": "Debes completar el rol funcional.",
        "salary_structure_invalid_functional_role": "El rol funcional seleccionado no es valido.",
        "salary_structure_activity_required": "Debes seleccionar una actividad.",
        "salary_structure_remuneration_type_required": "Debes seleccionar un tipo de remuneración.",
        "salary_structure_invalid_remuneration_type": "El tipo de remuneración seleccionado no es válido.",
        "salary_structure_invalid_divisions": "Las divisiones seleccionadas no son válidas.",
        "salary_structure_payment_type_required": "Debes seleccionar un tipo de pago.",
        "salary_structure_invalid_payment_type": "El tipo de pago seleccionado no es válido.",
        "salary_structure_invalid_status": "El estado seleccionado no es valido.",
        "salary_structure_invalid_workload_hours": "La carga horaria debe ser mayor o igual a cero.",
        "salary_structure_duplicate_role_activity": "Ya existe una Estructura Salarial activa con ese rol, actividad, divisiones y tipo de remuneración.",
        "salary_structure_forbidden": "No tienes permisos para administrar estructuras salariales.",
        "salary_structure_unknown_error": "No pudimos completar la operacion sobre la estructura salarial. Vuelve a intentarlo.",
        "staff_member_created": "El colaborador se creó correctamente.",
        "staff_member_updated": "El colaborador se actualizó correctamente.",
        "staff_member_not_found": "No encontramos el colaborador seleccionado.",
        "staff_member_first_name_required": "Debes completar el nombre del colaborador.",
        "staff_member_last_name_required": "Debes completar el apellido del colaborador.",
        "staff_member_dni_required": "Debes completar el DNI.",
        "staff_member_invalid_dni": "El DNI ingresado no es válido.",
        "staff_member_invalid_cuit_cuil": "Revisá el formato del CUIT/CUIL (XX-XXXXXXXX-X).",
        "staff_member_invalid_cuit_dv": "El CUIT/CUIL ingresado no es válido.",
        "staff_member_vinculo_required": "Debes seleccionar un tipo de vínculo.",
        "staff_member_invalid_vinculo": "El tipo de vínculo seleccionado no es válido.",
        "staff_member_email_invalid": "El email ingresado no es válido.",
        "staff_member_phone_invalid": "El formato del teléfono no es válido.",
        "staff_member_invalid_hire_date": "La fecha de alta no es válida.",
        "staff_member_duplicate_dni": "Ya existe un colaborador con ese DNI.",
        "staff_member_duplicate_cuit_cuil": "Ya existe un colaborador con ese CUIT/CUIL.",
        "staff_member_forbidden": "No tenés permisos para administrar colaboradores.",
        "staff_member_unknown_error": "No pudimos completar la operación sobre el colaborador. Volvé a intentarlo.",
        "staff_contract_created": "El contrato se creo correctamente.",
        "staff_contract_updated": "El contrato se actualizo correctamente.",
        "staff_contract_finalized": "El contrato se finalizo correctamente.",
        "staff_contract_not_found": "No encontramos el contrato seleccionado.",
        "staff_contract_member_required": "Debes seleccionar un colaborador.",
        "staff_contract_structure_required": "Debes seleccionar una Estructura Salarial.",
        "staff_contract_start_date_required": "Debes completar la fecha de inicio.",
        "staff_contract_end_date_before_start": "La fecha de fin no puede ser anterior a la fecha de inicio.",
        "staff_contract_start_date_too_old": "La fecha de inicio no puede ser mas de 30 dias hacia atras.",
        "staff_contract_agreed_amount_required": "Debes completar el monto acordado cuando el contrato no usa el monto de la estructura.",
        "staff_contract_agreed_amount_must_be_positive": "El monto acordado debe ser mayor a cero.",
        "staff_contract_frozen_amount_required": "Debes completar el monto congelado.",
        "staff_contract_frozen_amount_must_be_positive": "El monto congelado debe ser mayor a cero.",
        "staff_contract_structure_already_taken": "La Estructura Salarial ya tiene un contrato vigente. Finalizalo primero.",
        "staff_contract_member_not_active": "El colaborador seleccionado esta inactivo.",
        "staff_contract_structure_not_active": "La Estructura Salarial seleccionada esta inactiva.",
        "staff_contract_current_version_not_found": "No encontramos la version vigente del monto de la Estructura Salarial.",
        "staff_contract_invalid_end_date": "La fecha de fin no es valida.",
        "staff_contract_end_date_too_far": "La fecha de fin no puede superar los 10 años desde el inicio.",
        "staff_contract_already_finalized": "El contrato ya fue finalizado.",
        "staff_contract_invalid_status": "El estado del contrato no permite esta operacion.",
        "staff_contract_forbidden": "No tienes permisos para administrar contratos.",
        "staff_contract_unknown_error": "No pudimos completar la operacion sobre el contrato. Vuelve a intentarlo.",
        "staff_contract_initial_amount_required": "Debes completar el monto inicial del contrato.",
        "staff_contract_initial_amount_invalid": "El monto inicial debe ser mayor a cero.",
        "staff_contract_invalid_start_date": "La fecha de inicio no es válida.",
        "salary_revision_created": "La revisión salarial se creó correctamente.",
        "salary_revision_bulk_created": "Revisiones salariales aplicadas correctamente.",
        "salary_revision_contract_not_active": "Solo se pueden crear revisiones sobre contratos vigentes.",
        "salary_revision_amount_required": "Debes completar el monto.",
        "salary_revision_amount_must_be_positive": "El monto debe ser mayor a cero.",
        "salary_revision_effective_date_required": "Debes completar la fecha de vigencia.",
        "salary_revision_invalid_effective_date": "La fecha de vigencia debe ser posterior a la revisión anterior y estar dentro del contrato.",
        "salary_revision_no_contracts_selected": "Debes seleccionar al menos un contrato.",
        "salary_revision_reason_required": "Debes completar el motivo de la revisión masiva.",
        "salary_revision_value_required": "Debes completar el valor del ajuste.",
        "salary_revision_value_must_be_positive": "El valor debe ser mayor a cero.",
        "salary_revision_invalid_adjustment_type": "El tipo de ajuste seleccionado no es válido.",
        "salary_revision_current_not_found": "No encontramos la revisión salarial vigente.",
        "salary_revision_forbidden": "No tienes permisos para gestionar revisiones salariales.",
        "salary_revision_unknown_error": "No pudimos completar la operación sobre la revisión salarial. Volvé a intentarlo.",
        "contract_attachment_uploaded": "Adjunto subido correctamente.",
        "contract_attachment_deleted": "Adjunto eliminado correctamente.",
        "contract_attachment_not_found": "No encontramos el adjunto seleccionado.",
        "contract_attachment_file_missing": "Seleccioná un archivo para subir.",
        "contract_attachment_file_too_large": "El archivo supera el límite de 10 MB.",
        "contract_attachment_file_type_not_allowed": "Tipo de archivo no permitido. Usá PDF, DOC/DOCX o imágenes.",
        "contract_attachment_forbidden": "No tenés permisos para gestionar adjuntos de contratos.",
        "contract_attachment_unknown_error": "No pudimos completar la operación sobre el adjunto. Volvé a intentarlo."
      }
    },
    "invitations": {
      "section_title": "Crear usuario",
      "section_description": "El usuario podra ingresar a la app con su cuenta de Google al iniciar sesion por primera vez.",
      "toggle_cta": "+ Crear usuario",
      "email_label": "Email del usuario",
      "roles_label": "Roles a asignar",
      "invite_cta": "Crear usuario",
      "invite_loading": "Creando usuario...",
      "cancel_cta": "Cancelar",
      "email_placeholder": "usuario@ejemplo.com",
      "feedback": {
        "invitation_created": "Usuario creado correctamente.",
        "already_member": "Ese usuario ya pertenece al club activo.",
        "already_invited": "Ya existe un usuario pendiente de primer ingreso con ese email.",
        "email_required": "Debes completar un email.",
        "email_invalid": "Debes ingresar un email valido.",
        "role_required": "Debes seleccionar al menos un rol.",
        "roles_required": "Debes seleccionar al menos un rol.",
        "invalid_role": "Alguno de los roles seleccionados no es valido.",
        "forbidden": "No tienes permisos para crear usuarios en este club.",
        "unknown_error": "No pudimos crear el usuario. Vuelve a intentarlo."
      }
    },
    "members": {
      "section_title": "Usuarios",
      "section_description_singular": "Personas habilitadas en este club · 1 activo",
      "section_description_plural": "Personas habilitadas en este club · {count} activos",
      "info_banner": "Usuarios habilitados para {clubName}. Cada persona puede tener uno o varios roles (ej. Tesoreria + Admin). Los permisos se acumulan al sumar roles. Para accesos a medida, crea un usuario con permisos granulares.",
      "filter_all_label": "Todos",
      "active_status_label": "Activo",
      "empty_title": "No hay usuarios para mostrar",
      "empty_description": "Cuando crees usuarios en este club, apareceran listados aqui.",
      "current_user_badge": "Tu usuario",
      "pending_badge": "Pendiente de aprobacion",
      "name_label": "Nombre",
      "email_label": "Email",
      "role_label": "Rol",
      "roles_label": "Roles",
      "status_label": "Estado",
      "actions_label": "Acciones",
      "joined_at_label": "Ingreso al club",
      "approve_cta": "Aprobar acceso",
      "update_role_cta": "Actualizar rol",
      "update_roles_cta": "Actualizar roles",
      "update_roles_cancel_cta": "Cancelar",
      "approve_loading": "Aprobando acceso...",
      "update_roles_loading": "Actualizando roles...",
      "remove_cta": "Remover miembro",
      "leave_club_cta": "Salir del club",
      "remove_loading": "Removiendo membresia...",
      "remove_dialog_title": "Confirmar remocion",
      "remove_dialog_description": "Esta accion eliminara la membresia del club activo.",
      "remove_dialog_member_label": "Miembro seleccionado",
      "remove_dialog_confirm_cta": "Confirmar remocion",
      "remove_dialog_cancel_cta": "Cancelar",
      "role_placeholder": "Selecciona un rol",
      "roles": {
        "admin": "Admin",
        "rrhh": "RRHH",
        "secretaria": "Secretaria",
        "tesoreria": "Tesoreria"
      },
      "statuses": {
        "pendiente_aprobacion": "Pendiente de aprobacion",
        "activo": "Activo",
        "inactivo": "Inactivo"
      },
      "feedback": {
        "membership_approved": "La membresia fue aprobada y el rol quedo asignado.",
        "membership_roles_updated": "Los roles del miembro se actualizaron correctamente.",
        "membership_removed": "La membresia fue removida del club activo.",
        "self_removed": "Tu membresia fue removida del club activo.",
        "forbidden": "No tienes permisos para realizar esta accion.",
        "invalid_role": "Debes seleccionar al menos un rol valido.",
        "member_not_found": "No encontramos la membresia seleccionada en el club activo.",
        "membership_not_pending": "Solo puedes aprobar membresias que sigan pendientes.",
        "membership_not_active": "Solo puedes cambiar el rol de membresias activas.",
        "last_admin_required": "Debe existir al menos un admin activo en el club.",
        "unknown_error": "No pudimos completar la accion. Vuelve a intentarlo."
      }
    },
    "treasury": {
      "section_title": "Tesoreria",
      "section_description": "Configura cuentas, categorias y actividades del club activo para la operatoria diaria segun visibilidad por rol.",
      "accounts_title": "Cuentas",
      "accounts_description": "Administra las cuentas disponibles para Secretaria y Tesoreria segun su visibilidad.",
      "categories_title": "Categorias",
      "categories_description": "Define las sub categorias disponibles para los movimientos del club activo segun visibilidad.",
      "section_combined_title": "Categorias y actividades",
      "taxonomy_eyebrow": "Taxonomia de movimientos (ingresos / egresos).",
      "filter_all_label": "Todas",
      "filter_ingresos_label": "Ingresos",
      "filter_egresos_label": "Egresos",
      "subcategories_count_singular": "1 subcategoria",
      "subcategories_count_plural": "{count} subcategorias",
      "create_category_short_cta": "Cargar Sub Categoria",
      "create_activity_short_cta": "+ Actividad",
      "empty_groups_filter": "Sin categorias para este filtro.",
      "activities_title": "Actividades",
      "activities_description": "Administra las actividades deportivas disponibles para cada rol segun visibilidad.",
      "calendar_events_title": "Eventos disponibles para imputacion",
      "calendar_events_description": "Define que eventos sincronizados del club pueden ser seleccionados por Secretaria al imputar movimientos.",
      "calendar_events_enabled_label": "Disponible para imputacion",
      "calendar_events_without_date": "Sin fecha informada",
      "movement_types_title": "Tipos de movimiento",
      "movement_types_description": "Muestra los tipos fijos del sistema que Secretaria usara en los movimientos manuales.",
      "receipt_formats_title": "Sistema de socios",
      "receipt_formats_description": "Configura el nombre del campo, el tipo de formato aceptado y la visibilidad por rol.",
      "create_account_cta": "Crear cuenta",
      "edit_account_cta": "Editar cuenta",
      "save_account_cta": "Guardar cuenta",
      "save_account_loading": "Guardando cuenta...",
      "update_account_cta": "Actualizar cuenta",
      "update_account_loading": "Actualizando cuenta...",
      "create_category_cta": "Crear sub categoria",
      "edit_category_cta": "Editar sub categoria",
      "save_category_cta": "Guardar sub categoria",
      "save_category_loading": "Guardando sub categoria...",
      "update_category_cta": "Actualizar sub categoria",
      "update_category_loading": "Actualizando sub categoria...",
      "create_activity_cta": "Crear actividad",
      "edit_activity_cta": "Editar actividad",
      "save_activity_cta": "Guardar actividad",
      "save_activity_loading": "Guardando actividad...",
      "update_activity_cta": "Actualizar actividad",
      "update_activity_loading": "Actualizando actividad...",
      "save_calendar_event_cta": "Guardar evento",
      "save_calendar_event_loading": "Guardando evento...",
      "create_receipt_format_cta": "Crear formato",
      "edit_receipt_format_cta": "Editar sistema de socios",
      "save_receipt_format_cta": "Guardar sistema de socios",
      "save_receipt_format_loading": "Guardando...",
      "update_receipt_format_cta": "Actualizar sistema de socios",
      "update_receipt_format_loading": "Actualizando...",
      "account_name_label": "Nombre",
      "category_name_label": "Nombre",
      "sub_category_name_label": "Sub Categoria",
      "category_description_label": "Descripcion",
      "parent_category_label": "Categoria",
      "parent_category_placeholder": "Selecciona una categoria",
      "category_type_label": "Tipo",
      "category_type_badge": "Tipo",
      "parent_category_badge": "Categoria",
      "system_category_badge": "Base",
      "activity_name_label": "Nombre",
      "receipt_name_label": "Nombre",
      "receipt_validation_type_options": {
        "numeric": "Numero",
        "pattern": "Alfanumerico"
      },
      "account_type_label": "Tipo de cuenta",
      "account_visibility_label": "Visibilidad",
      "account_scope_label": "Ambito",
      "account_currencies_label": "Moneda",
      "account_currencies_helper": "Cada cuenta opera en una unica moneda. Para operar la misma entidad en ARS y USD, cree dos cuentas separadas.",
      "account_name_placeholder": "ej. Efectivo caja chica",
      "account_name_helper": "Nombre con el que aparecera en reportes y listados.",
      "account_name_banco_auto_placeholder": "Se compone al elegir entidad y tipo de cuenta.",
      "account_name_banco_helper": "El nombre se genera automaticamente con Entidad + Tipo de cuenta.",
      "account_type_cards": {
        "bancaria": "Banco",
        "billetera_virtual": "Billetera",
        "efectivo": "Efectivo"
      },
      "account_type_emojis": {
        "bancaria": "🏦",
        "billetera_virtual": "📱",
        "efectivo": "💵"
      },
      "bank_entity_label": "Entidad bancaria",
      "bank_entity_placeholder": "Selecciona una entidad",
      "bank_entities": [
        "Banco Nacion",
        "Banco Galicia",
        "Banco Santander",
        "Banco BBVA",
        "Banco Macro",
        "Banco Credicoop",
        "Banco Provincia",
        "Banco Ciudad",
        "HSBC",
        "ICBC"
      ],
      "wallet_provider_label": "Proveedor",
      "wallet_provider_placeholder": "Selecciona un proveedor",
      "wallet_providers": [
        "Mercado Pago",
        "Uala",
        "Personal Pay",
        "Naranja X",
        "Otro"
      ],
      "bank_account_subtype_label": "Tipo de cuenta bancaria",
      "bank_account_subtype_placeholder": "Selecciona un tipo",
      "bank_account_subtypes": {
        "cuenta_corriente": "Cuenta corriente",
        "caja_ahorro": "Caja de ahorro"
      },
      "account_number_label": "Numero de cuenta",
      "account_number_placeholder": "0000-00000000-0",
      "cbu_cvu_label": "CBU / CVU",
      "cbu_cvu_placeholder": "22 digitos",
      "alias_label": "Alias",
      "alias_placeholder": "ourclub.tesoreria.mp",
      "alias_helper": "Solo letras, numeros y puntos.",
      "initial_balance_label": "Saldo inicial",
      "initial_balance_helper": "Saldo inicial de la moneda operativa. Podes dejar en 0.",
      "create_account_description": "Dar de alta una cuenta bancaria, billetera o efectivo.",
      "edit_account_description": "Actualiza los datos de la cuenta.",
      "cancel_cta": "Cancelar",
      "visibility_secretaria_checkbox": "Disponible para Secretaria",
      "visibility_tesoreria_checkbox": "Disponible para Tesoreria",
      "account_type_placeholder": "Selecciona un tipo",
      "receipt_validation_type_label": "Tipo de validacion",
      "receipt_min_label": "Proximo recibo",
      "receipt_pattern_label": "Patron",
      "receipt_example_label": "Ejemplo",
      "receipt_formats_read_only": "La configuracion del sistema de socios define el nombre del campo, el tipo de formato aceptado y la visibilidad por rol.",
      "movement_type_selection_label": "Tipos del sistema",
      "movement_type_impacts": {
        "ingreso": "Incrementa saldo",
        "egreso": "Reduce saldo"
      },
      "visibility_label": "Visible para Secretaria",
      "visibility_visible": "Visible",
      "visibility_hidden": "Oculta",
      "status_label": "Estado",
      "emoji_label": "Emoji",
      "emoji_placeholder": "Selecciona un emoji",
      "default_account_emoji": "💼",
      "default_category_emoji": "📁",
      "default_activity_emoji": "🏅",
      "empty_accounts": "Todavia no hay cuentas configuradas para el club activo.",
      "empty_categories": "Todavia no hay sub categorias configuradas para el club activo.",
      "empty_categories_search": "No encontramos resultados para la busqueda.",
      "empty_activities": "Todavia no hay actividades configuradas para el club activo.",
      "empty_calendar_events": "No hay eventos sincronizados disponibles para el club activo.",
      "empty_receipt_formats": "No pudimos cargar la configuracion del sistema de socios del club activo.",
      "account_types": {
        "efectivo": "Efectivo",
        "bancaria": "Bancaria",
        "billetera_virtual": "Billetera virtual"
      },
      "account_scopes": {
        "secretaria": "Secretaria",
        "tesoreria": "Tesoreria"
      },
      "account_visibility_options": {
        "secretaria": "Secretaria",
        "tesoreria": "Tesoreria"
      },
      "emoji_options": {
        "accounts": [
          "💵",
          "🏦",
          "💼",
          "📈",
          "🏛️"
        ],
        "categories": [
          "🏠",
          "🧾",
          "🎉",
          "📝",
          "🏛️",
          "👕",
          "📈",
          "🏆",
          "🛠️",
          "🏗️",
          "📁",
          "🤝",
          "🔌",
          "💼",
          "🎯",
          "💸",
          "🎽",
          "⚖️",
          "💳"
        ],
        "activities": [
          "🏅",
          "⚽",
          "🥊",
          "🏑",
          "🏀"
        ]
      },
      "category_movement_types": {
        "ingreso": "Ingreso",
        "egreso": "Egreso",
        "saldo": "Saldo"
      },
      "statuses": {
        "active": "Activa",
        "inactive": "Inactiva"
      },
      "receipt_validation_types": {
        "numeric": "Numerico",
        "pattern": "Nomenclatura"
      },
      "currency_options": {
        "ARS": "ARS",
        "USD": "USD"
      },
      "feedback": {
        "account_created": "La cuenta fue registrada correctamente en el club activo.",
        "account_updated": "La cuenta fue actualizada correctamente.",
        "category_created": "La sub categoria fue registrada correctamente en el club activo.",
        "category_updated": "La sub categoria fue actualizada correctamente.",
        "activity_created": "La actividad fue registrada correctamente en el club activo.",
        "activity_updated": "La actividad fue actualizada correctamente.",
        "receipt_format_created": "El formato de recibo fue registrado correctamente en el club activo.",
        "receipt_format_updated": "Sistema de socios actualizado correctamente.",
        "account_name_required": "Debes completar el nombre de la cuenta.",
        "account_type_required": "Debes seleccionar un tipo de cuenta.",
        "category_name_required": "Debes completar la sub categoria.",
        "category_description_required": "Debes completar la descripcion de la sub categoria.",
        "category_parent_required": "Debes seleccionar una categoria.",
        "activity_name_required": "Debes completar el nombre de la actividad.",
        "receipt_format_name_required": "Debes completar el nombre del sistema de socios.",
        "receipt_format_name_too_long": "El nombre no puede superar los 50 caracteres.",
        "receipt_format_name_invalid": "El nombre solo puede contener letras, numeros y espacios.",
        "receipt_format_invalid_type": "El tipo de formato seleccionado no es valido.",
        "receipt_format_forbidden": "No tienes permisos para administrar la configuracion del sistema de socios.",
        "receipt_format_admin_config_missing": "Falta configurar las credenciales de administrador de Supabase para guardar el sistema de socios.",
        "receipt_format_unknown_error": "No pudimos guardar la configuracion del sistema de socios. Vuelve a intentarlo.",
        "receipt_format_min_required": "Debes completar un valor minimo valido para el formato numerico.",
        "receipt_format_pattern_required": "Debes completar un patron para el formato con nomenclatura.",
        "account_currencies_required": "Debes seleccionar la moneda operativa de la cuenta.",
        "account_single_currency_required": "Cada cuenta debe operar en una unica moneda.",
        "bank_entity_required": "Debes seleccionar la entidad bancaria.",
        "bank_account_subtype_required": "Debes seleccionar el tipo de cuenta bancaria.",
        "account_visibility_required": "Debes seleccionar al menos una visibilidad.",
        "duplicate_account_name": "Ya existe una cuenta con ese nombre en el club activo.",
        "duplicate_category_name": "Ya existe una sub categoria con ese nombre en el club activo.",
        "duplicate_activity_name": "Ya existe una actividad con ese nombre en el club activo.",
        "duplicate_receipt_format_name": "Ya existe un formato de recibo activo con ese nombre en el club activo.",
        "invalid_account_type": "El tipo de cuenta seleccionado no es valido.",
        "invalid_emoji_option": "Debes seleccionar un emoji valido del listado del sistema.",
        "invalid_account_currency": "La moneda seleccionada para la cuenta debe ser ARS o USD.",
        "invalid_cbu": "Revisa el formato del CBU/CVU (debe tener 22 digitos).",
        "invalid_alias": "El alias solo puede contener letras, numeros y puntos.",
        "invalid_initial_balance": "El saldo inicial debe ser un numero mayor o igual a 0.",
        "invalid_bank_account_subtype": "El tipo de cuenta bancaria seleccionado no es valido.",
        "invalid_config_status": "El estado seleccionado no es valido.",
        "invalid_receipt_validation_type": "El tipo de validacion seleccionado no es valido.",
        "account_not_found": "No encontramos la cuenta seleccionada en el club activo.",
        "category_not_found": "No encontramos la sub categoria seleccionada en el club activo.",
        "activity_not_found": "No encontramos la actividad seleccionada en el club activo.",
        "receipt_format_not_found": "No encontramos el formato de recibo seleccionado en el club activo.",
        "calendar_event_updated": "La disponibilidad del evento para imputacion se actualizo correctamente.",
        "calendar_event_not_found": "No encontramos el evento seleccionado en el club activo.",
        "treasury_admin_config_missing": "Falta configurar las credenciales de administrador de Supabase para guardar la configuracion de tesoreria.",
        "forbidden": "No tienes permisos para administrar la configuracion de tesoreria.",
        "unknown_error": "No pudimos guardar la configuracion de tesoreria. Vuelve a intentarlo."
      }
    }
  }
};
