-- Performance advisor 0005 (unused_index): 47 indices con scan=0
--
-- DECISION: NO dropear ninguno hoy. Razones:
--
-- 1. La metrica scan=0 mide uso desde el ultimo restart del servidor
--    o pg_stat_reset(). No es "nunca usado", es "no usado desde el
--    ultimo reset". Las stats actuales tienen pocos dias de vida.
--
-- 2. Clasificacion de los 47:
--    - 6 *_pkey (primary keys, intocables)
--    - 6 *_unique_*, *_uidx, *_key (UNIQUE constraints — soportan
--      validacion en INSERT/UPDATE aunque pg_stat no cuente esos
--      "scans")
--    - 32 FK covering nuevos del refactor 2026-04-27 (commits
--      38c344d y 2ae031c). Falsos positivos esperables: la app no
--      ha tenido trafico productivo significativo desde su creacion.
--    - 13 indices legacy intencionales del autor original. Son
--      composites o partial que cubren queries especificas (listado
--      mensual de movimientos, busqueda por display_id, listado por
--      estado, etc.). Dropearlos a ciegas degrada queries a seq scan.
--
-- 3. Para resolver REAL hay que:
--    a) Resetear stats: select pg_stat_reset(); (requiere superuser
--       — correr desde el dashboard de Supabase: Project Settings →
--       Database → Run SQL como rol postgres).
--    b) Dejar pasar 1-2 semanas de trafico productivo con cada flujo
--       ejecutandose al menos 1 vez (smoke test E2E + uso real).
--    c) Volver a correr get_advisors performance.
--    d) Recien entonces dropear los que sigan con scan=0.
--
-- Esta migracion es solo documentacion. No ejecuta DDL.
select 'Ver comentarios — no DDL aplicada' as note;
